/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef NSTAGENTMODULES_H
#define NSTAGENTMODULES_H

/* function declarations */
void init_nstAgentModules(void);
Netsnmp_Node_Handler handle_nstAgentModuleObject;
Netsnmp_Node_Handler handle_nstAgentSubagentObject;
Netsnmp_Node_Handler handle_nstAgentPluginObject;

#endif /* NSTAGENTMODULES_H */
