CC=gcc -Wall -ggdb3

all:hexstrdump hexstrtosiug5x hexstrtocbytes

hexstrdump: hexstrdump.c
	${CC} $^ ${LINK} -o $@ 

hexstrtosiug5x: hexstrtosiug5x.c
	${CC} $^ ${LINK} -o $@ 

hexstrtocbytes: hexstrtocbytes.c
	${CC} $^ ${LINK} -o $@ 
