/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-OM-DataTypes"
 * 	found in "MAP-OM-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#include "ActivateTraceModeArg.h"

static asn_TYPE_member_t asn_MBR_ActivateTraceModeArg_1[] = {
	{ ATF_POINTER, 1, offsetof(struct ActivateTraceModeArg, imsi),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IMSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"imsi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActivateTraceModeArg, traceReference),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TraceReference,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"traceReference"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ActivateTraceModeArg, traceType),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TraceType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"traceType"
		},
	{ ATF_POINTER, 8, offsetof(struct ActivateTraceModeArg, omc_Id),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AddressString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"omc-Id"
		},
	{ ATF_POINTER, 7, offsetof(struct ActivateTraceModeArg, extensionContainer),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
	{ ATF_POINTER, 6, offsetof(struct ActivateTraceModeArg, traceReference2),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TraceReference2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"traceReference2"
		},
	{ ATF_POINTER, 5, offsetof(struct ActivateTraceModeArg, traceDepthList),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TraceDepthList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"traceDepthList"
		},
	{ ATF_POINTER, 4, offsetof(struct ActivateTraceModeArg, traceNE_TypeList),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TraceNE_TypeList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"traceNE-TypeList"
		},
	{ ATF_POINTER, 3, offsetof(struct ActivateTraceModeArg, traceInterfaceList),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TraceInterfaceList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"traceInterfaceList"
		},
	{ ATF_POINTER, 2, offsetof(struct ActivateTraceModeArg, traceEventList),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TraceEventList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"traceEventList"
		},
	{ ATF_POINTER, 1, offsetof(struct ActivateTraceModeArg, traceCollectionEntity),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GSN_Address,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"traceCollectionEntity"
		},
};
static const ber_tlv_tag_t asn_DEF_ActivateTraceModeArg_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ActivateTraceModeArg_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* imsi */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* traceReference */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* traceType */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* omc-Id */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* extensionContainer */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* traceReference2 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* traceDepthList */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* traceNE-TypeList */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* traceInterfaceList */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* traceEventList */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 } /* traceCollectionEntity */
};
static asn_SEQUENCE_specifics_t asn_SPC_ActivateTraceModeArg_specs_1 = {
	sizeof(struct ActivateTraceModeArg),
	offsetof(struct ActivateTraceModeArg, _asn_ctx),
	asn_MAP_ActivateTraceModeArg_tag2el_1,
	11,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* Start extensions */
	12	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ActivateTraceModeArg = {
	"ActivateTraceModeArg",
	"ActivateTraceModeArg",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ActivateTraceModeArg_tags_1,
	sizeof(asn_DEF_ActivateTraceModeArg_tags_1)
		/sizeof(asn_DEF_ActivateTraceModeArg_tags_1[0]), /* 1 */
	asn_DEF_ActivateTraceModeArg_tags_1,	/* Same as above */
	sizeof(asn_DEF_ActivateTraceModeArg_tags_1)
		/sizeof(asn_DEF_ActivateTraceModeArg_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ActivateTraceModeArg_1,
	11,	/* Elements count */
	&asn_SPC_ActivateTraceModeArg_specs_1	/* Additional specs */
};

