/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-CH-DataTypes"
 * 	found in "MAP-CH-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#ifndef	_CallTerminationIndicator_H_
#define	_CallTerminationIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CallTerminationIndicator {
	CallTerminationIndicator_terminateCallActivityReferred	= 0,
	CallTerminationIndicator_terminateAllCallActivities	= 1
	/*
	 * Enumeration is extensible
	 */
} e_CallTerminationIndicator;

/* CallTerminationIndicator */
typedef long	 CallTerminationIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallTerminationIndicator;
asn_struct_free_f CallTerminationIndicator_free;
asn_struct_print_f CallTerminationIndicator_print;
asn_constr_check_f CallTerminationIndicator_constraint;
ber_type_decoder_f CallTerminationIndicator_decode_ber;
der_type_encoder_f CallTerminationIndicator_encode_der;
xer_type_decoder_f CallTerminationIndicator_decode_xer;
xer_type_encoder_f CallTerminationIndicator_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CallTerminationIndicator_H_ */
#include <asn_internal.h>
