/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-SS-DataTypes"
 * 	found in "MAP-SS-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#ifndef	_CallBarringFeature_H_
#define	_CallBarringFeature_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SS-Status.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BasicServiceCode;

/* CallBarringFeature */
typedef struct CallBarringFeature {
	struct BasicServiceCode	*basicService	/* OPTIONAL */;
	SS_Status_t	*ss_Status	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CallBarringFeature_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallBarringFeature;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BasicServiceCode.h"

#endif	/* _CallBarringFeature_H_ */
#include <asn_internal.h>
