/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-CH-DataTypes"
 * 	found in "MAP-CH-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#ifndef	_CCBS_SubscriberStatus_H_
#define	_CCBS_SubscriberStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CCBS_SubscriberStatus {
	CCBS_SubscriberStatus_ccbsNotIdle	= 0,
	CCBS_SubscriberStatus_ccbsIdle	= 1,
	CCBS_SubscriberStatus_ccbsNotReachable	= 2
	/*
	 * Enumeration is extensible
	 */
} e_CCBS_SubscriberStatus;

/* CCBS-SubscriberStatus */
typedef long	 CCBS_SubscriberStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CCBS_SubscriberStatus;
asn_struct_free_f CCBS_SubscriberStatus_free;
asn_struct_print_f CCBS_SubscriberStatus_print;
asn_constr_check_f CCBS_SubscriberStatus_constraint;
ber_type_decoder_f CCBS_SubscriberStatus_decode_ber;
der_type_encoder_f CCBS_SubscriberStatus_encode_der;
xer_type_decoder_f CCBS_SubscriberStatus_decode_xer;
xer_type_encoder_f CCBS_SubscriberStatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CCBS_SubscriberStatus_H_ */
#include <asn_internal.h>
