/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-SS-DataTypes"
 * 	found in "MAP-SS-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#ifndef	_CliRestrictionOption_H_
#define	_CliRestrictionOption_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CliRestrictionOption {
	CliRestrictionOption_permanent	= 0,
	CliRestrictionOption_temporaryDefaultRestricted	= 1,
	CliRestrictionOption_temporaryDefaultAllowed	= 2
} e_CliRestrictionOption;

/* CliRestrictionOption */
typedef long	 CliRestrictionOption_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CliRestrictionOption;
asn_struct_free_f CliRestrictionOption_free;
asn_struct_print_f CliRestrictionOption_print;
asn_constr_check_f CliRestrictionOption_constraint;
ber_type_decoder_f CliRestrictionOption_decode_ber;
der_type_encoder_f CliRestrictionOption_encode_der;
xer_type_decoder_f CliRestrictionOption_decode_xer;
xer_type_encoder_f CliRestrictionOption_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CliRestrictionOption_H_ */
#include <asn_internal.h>
