/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#include "CurrentSecurityContext.h"

static asn_TYPE_member_t asn_MBR_CurrentSecurityContext_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentSecurityContext, choice.gsm_SecurityContextData),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GSM_SecurityContextData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gsm-SecurityContextData"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentSecurityContext, choice.umts_SecurityContextData),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UMTS_SecurityContextData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"umts-SecurityContextData"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_CurrentSecurityContext_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gsm-SecurityContextData */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* umts-SecurityContextData */
};
static asn_CHOICE_specifics_t asn_SPC_CurrentSecurityContext_specs_1 = {
	sizeof(struct CurrentSecurityContext),
	offsetof(struct CurrentSecurityContext, _asn_ctx),
	offsetof(struct CurrentSecurityContext, present),
	sizeof(((struct CurrentSecurityContext *)0)->present),
	asn_MAP_CurrentSecurityContext_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CurrentSecurityContext = {
	"CurrentSecurityContext",
	"CurrentSecurityContext",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_CurrentSecurityContext_1,
	2,	/* Elements count */
	&asn_SPC_CurrentSecurityContext_specs_1	/* Additional specs */
};

