/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#include "EPC-AV.h"

static asn_TYPE_member_t asn_MBR_EPC_AV_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EPC_AV, rand),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_RAND,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rand"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPC_AV, xres),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_XRES,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"xres"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPC_AV, autn),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_AUTN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"autn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPC_AV, kasme),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_KASME,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"kasme"
		},
	{ ATF_POINTER, 1, offsetof(struct EPC_AV, extensionContainer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
};
static const ber_tlv_tag_t asn_DEF_EPC_AV_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EPC_AV_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 3 }, /* rand */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, -1, 2 }, /* xres */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, -2, 1 }, /* autn */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, -3, 0 }, /* kasme */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, 0, 0 } /* extensionContainer */
};
static asn_SEQUENCE_specifics_t asn_SPC_EPC_AV_specs_1 = {
	sizeof(struct EPC_AV),
	offsetof(struct EPC_AV, _asn_ctx),
	asn_MAP_EPC_AV_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_EPC_AV = {
	"EPC-AV",
	"EPC-AV",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_EPC_AV_tags_1,
	sizeof(asn_DEF_EPC_AV_tags_1)
		/sizeof(asn_DEF_EPC_AV_tags_1[0]), /* 1 */
	asn_DEF_EPC_AV_tags_1,	/* Same as above */
	sizeof(asn_DEF_EPC_AV_tags_1)
		/sizeof(asn_DEF_EPC_AV_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_EPC_AV_1,
	5,	/* Elements count */
	&asn_SPC_EPC_AV_specs_1	/* Additional specs */
};

