/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#include "Ext-SS-InfoFor-CSE.h"

static asn_TYPE_member_t asn_MBR_Ext_SS_InfoFor_CSE_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Ext_SS_InfoFor_CSE, choice.forwardingInfoFor_CSE),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ext_ForwardingInfoFor_CSE,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"forwardingInfoFor-CSE"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Ext_SS_InfoFor_CSE, choice.callBarringInfoFor_CSE),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ext_CallBarringInfoFor_CSE,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callBarringInfoFor-CSE"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Ext_SS_InfoFor_CSE_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* forwardingInfoFor-CSE */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* callBarringInfoFor-CSE */
};
static asn_CHOICE_specifics_t asn_SPC_Ext_SS_InfoFor_CSE_specs_1 = {
	sizeof(struct Ext_SS_InfoFor_CSE),
	offsetof(struct Ext_SS_InfoFor_CSE, _asn_ctx),
	offsetof(struct Ext_SS_InfoFor_CSE, present),
	sizeof(((struct Ext_SS_InfoFor_CSE *)0)->present),
	asn_MAP_Ext_SS_InfoFor_CSE_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Ext_SS_InfoFor_CSE = {
	"Ext-SS-InfoFor-CSE",
	"Ext-SS-InfoFor-CSE",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Ext_SS_InfoFor_CSE_1,
	2,	/* Elements count */
	&asn_SPC_Ext_SS_InfoFor_CSE_specs_1	/* Additional specs */
};

