/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#include "LCS-PrivacyClass.h"

static asn_TYPE_member_t asn_MBR_LCS_PrivacyClass_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_PrivacyClass, ss_Code),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_SS_Code,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ss-Code"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LCS_PrivacyClass, ss_Status),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_Ext_SS_Status,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ss-Status"
		},
	{ ATF_POINTER, 6, offsetof(struct LCS_PrivacyClass, notificationToMSUser),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NotificationToMSUser,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"notificationToMSUser"
		},
	{ ATF_POINTER, 5, offsetof(struct LCS_PrivacyClass, externalClientList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExternalClientList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"externalClientList"
		},
	{ ATF_POINTER, 4, offsetof(struct LCS_PrivacyClass, plmnClientList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PLMNClientList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"plmnClientList"
		},
	{ ATF_POINTER, 3, offsetof(struct LCS_PrivacyClass, extensionContainer),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
	{ ATF_POINTER, 2, offsetof(struct LCS_PrivacyClass, ext_externalClientList),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ext_ExternalClientList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ext-externalClientList"
		},
	{ ATF_POINTER, 1, offsetof(struct LCS_PrivacyClass, serviceTypeList),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServiceTypeList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceTypeList"
		},
};
static const ber_tlv_tag_t asn_DEF_LCS_PrivacyClass_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LCS_PrivacyClass_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 1 }, /* ss-Code */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, -1, 0 }, /* ss-Status */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* notificationToMSUser */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 3, 0, 0 }, /* externalClientList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 4, 0, 0 }, /* plmnClientList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 5, 0, 0 }, /* extensionContainer */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 6, 0, 0 }, /* ext-externalClientList */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 7, 0, 0 } /* serviceTypeList */
};
static asn_SEQUENCE_specifics_t asn_SPC_LCS_PrivacyClass_specs_1 = {
	sizeof(struct LCS_PrivacyClass),
	offsetof(struct LCS_PrivacyClass, _asn_ctx),
	asn_MAP_LCS_PrivacyClass_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	9	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LCS_PrivacyClass = {
	"LCS-PrivacyClass",
	"LCS-PrivacyClass",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_LCS_PrivacyClass_tags_1,
	sizeof(asn_DEF_LCS_PrivacyClass_tags_1)
		/sizeof(asn_DEF_LCS_PrivacyClass_tags_1[0]), /* 1 */
	asn_DEF_LCS_PrivacyClass_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCS_PrivacyClass_tags_1)
		/sizeof(asn_DEF_LCS_PrivacyClass_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_LCS_PrivacyClass_1,
	8,	/* Elements count */
	&asn_SPC_LCS_PrivacyClass_specs_1	/* Additional specs */
};

