/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=all`
 */

#include "MAP-OPERATION.h"

static asn_TYPE_member_t asn_MBR_MAP_OPERATION_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MAP_OPERATION, choice.localValue),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_OperationLocalvalue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"localValue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAP_OPERATION, choice.globalValue),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"globalValue"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_MAP_OPERATION_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* localValue */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, 0, 0 } /* globalValue */
};
static asn_CHOICE_specifics_t asn_SPC_MAP_OPERATION_specs_1 = {
	sizeof(struct MAP_OPERATION),
	offsetof(struct MAP_OPERATION, _asn_ctx),
	offsetof(struct MAP_OPERATION, present),
	sizeof(((struct MAP_OPERATION *)0)->present),
	asn_MAP_MAP_OPERATION_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_MAP_OPERATION = {
	"MAP-OPERATION",
	"MAP-OPERATION",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_MAP_OPERATION_1,
	2,	/* Elements count */
	&asn_SPC_MAP_OPERATION_specs_1	/* Additional specs */
};

