/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-CommonDataTypes"
 * 	found in "MAP-CommonDataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#ifndef	_MaxMC_Bearers_H_
#define	_MaxMC_Bearers_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MaxMC-Bearers */
typedef long	 MaxMC_Bearers_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MaxMC_Bearers;
asn_struct_free_f MaxMC_Bearers_free;
asn_struct_print_f MaxMC_Bearers_print;
asn_constr_check_f MaxMC_Bearers_constraint;
ber_type_decoder_f MaxMC_Bearers_decode_ber;
der_type_encoder_f MaxMC_Bearers_encode_der;
xer_type_decoder_f MaxMC_Bearers_decode_xer;
xer_type_encoder_f MaxMC_Bearers_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MaxMC_Bearers_H_ */
#include <asn_internal.h>
