/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-CH-DataTypes"
 * 	found in "MAP-CH-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#ifndef	_MonitoringMode_H_
#define	_MonitoringMode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MonitoringMode {
	MonitoringMode_a_side	= 0,
	MonitoringMode_b_side	= 1
	/*
	 * Enumeration is extensible
	 */
} e_MonitoringMode;

/* MonitoringMode */
typedef long	 MonitoringMode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MonitoringMode;
asn_struct_free_f MonitoringMode_free;
asn_struct_print_f MonitoringMode_print;
asn_constr_check_f MonitoringMode_constraint;
ber_type_decoder_f MonitoringMode_decode_ber;
der_type_encoder_f MonitoringMode_encode_der;
xer_type_decoder_f MonitoringMode_decode_xer;
xer_type_encoder_f MonitoringMode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MonitoringMode_H_ */
#include <asn_internal.h>
