/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=all`
 */

#ifndef	_NewPassword_H_
#define	_NewPassword_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NumericString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NewPassword */
typedef NumericString_t	 NewPassword_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NewPassword;
asn_struct_free_f NewPassword_free;
asn_struct_print_f NewPassword_print;
asn_constr_check_f NewPassword_constraint;
ber_type_decoder_f NewPassword_decode_ber;
der_type_encoder_f NewPassword_encode_der;
xer_type_decoder_f NewPassword_decode_xer;
xer_type_encoder_f NewPassword_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NewPassword_H_ */
#include <asn_internal.h>
