/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#include "PrepareSubsequentHO-Arg.h"

static asn_TYPE_member_t asn_MBR_PrepareSubsequentHO_Arg_1[] = {
	{ ATF_POINTER, 1, offsetof(struct PrepareSubsequentHO_Arg, targetCellId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GlobalCellId,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"targetCellId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PrepareSubsequentHO_Arg, targetMSC_Number),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ISDN_AddressString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"targetMSC-Number"
		},
	{ ATF_POINTER, 6, offsetof(struct PrepareSubsequentHO_Arg, targetRNCId),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RNCId,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"targetRNCId"
		},
	{ ATF_POINTER, 5, offsetof(struct PrepareSubsequentHO_Arg, an_APDU),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AccessNetworkSignalInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"an-APDU"
		},
	{ ATF_POINTER, 4, offsetof(struct PrepareSubsequentHO_Arg, selectedRab_Id),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RAB_Id,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"selectedRab-Id"
		},
	{ ATF_POINTER, 3, offsetof(struct PrepareSubsequentHO_Arg, extensionContainer),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
	{ ATF_POINTER, 2, offsetof(struct PrepareSubsequentHO_Arg, geran_classmark),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GERAN_Classmark,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"geran-classmark"
		},
	{ ATF_POINTER, 1, offsetof(struct PrepareSubsequentHO_Arg, rab_ConfigurationIndicator),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rab-ConfigurationIndicator"
		},
};
static const ber_tlv_tag_t asn_DEF_PrepareSubsequentHO_Arg_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PrepareSubsequentHO_Arg_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* targetCellId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* targetMSC-Number */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* targetRNCId */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* an-APDU */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* selectedRab-Id */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* extensionContainer */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* geran-classmark */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* rab-ConfigurationIndicator */
};
static asn_SEQUENCE_specifics_t asn_SPC_PrepareSubsequentHO_Arg_specs_1 = {
	sizeof(struct PrepareSubsequentHO_Arg),
	offsetof(struct PrepareSubsequentHO_Arg, _asn_ctx),
	asn_MAP_PrepareSubsequentHO_Arg_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	9	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PrepareSubsequentHO_Arg = {
	"PrepareSubsequentHO-Arg",
	"PrepareSubsequentHO-Arg",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PrepareSubsequentHO_Arg_tags_1,
	sizeof(asn_DEF_PrepareSubsequentHO_Arg_tags_1)
		/sizeof(asn_DEF_PrepareSubsequentHO_Arg_tags_1[0]) - 1, /* 1 */
	asn_DEF_PrepareSubsequentHO_Arg_tags_1,	/* Same as above */
	sizeof(asn_DEF_PrepareSubsequentHO_Arg_tags_1)
		/sizeof(asn_DEF_PrepareSubsequentHO_Arg_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_PrepareSubsequentHO_Arg_1,
	8,	/* Elements count */
	&asn_SPC_PrepareSubsequentHO_Arg_specs_1	/* Additional specs */
};

