/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#include "ProcessAccessSignalling-Arg.h"

static asn_TYPE_member_t asn_MBR_ProcessAccessSignalling_Arg_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ProcessAccessSignalling_Arg, an_APDU),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AccessNetworkSignalInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"an-APDU"
		},
	{ ATF_POINTER, 9, offsetof(struct ProcessAccessSignalling_Arg, selectedUMTS_Algorithms),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SelectedUMTS_Algorithms,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"selectedUMTS-Algorithms"
		},
	{ ATF_POINTER, 8, offsetof(struct ProcessAccessSignalling_Arg, selectedGSM_Algorithm),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SelectedGSM_Algorithm,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"selectedGSM-Algorithm"
		},
	{ ATF_POINTER, 7, offsetof(struct ProcessAccessSignalling_Arg, chosenRadioResourceInformation),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChosenRadioResourceInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chosenRadioResourceInformation"
		},
	{ ATF_POINTER, 6, offsetof(struct ProcessAccessSignalling_Arg, selectedRab_Id),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RAB_Id,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"selectedRab-Id"
		},
	{ ATF_POINTER, 5, offsetof(struct ProcessAccessSignalling_Arg, extensionContainer),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
	{ ATF_POINTER, 4, offsetof(struct ProcessAccessSignalling_Arg, iUSelectedCodec),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Codec,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iUSelectedCodec"
		},
	{ ATF_POINTER, 3, offsetof(struct ProcessAccessSignalling_Arg, iuAvailableCodecsList),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CodecList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iuAvailableCodecsList"
		},
	{ ATF_POINTER, 2, offsetof(struct ProcessAccessSignalling_Arg, aoipSelectedCodecTarget),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AoIPCodec,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aoipSelectedCodecTarget"
		},
	{ ATF_POINTER, 1, offsetof(struct ProcessAccessSignalling_Arg, aoipAvailableCodecsListMap),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AoIPCodecsList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aoipAvailableCodecsListMap"
		},
};
static const ber_tlv_tag_t asn_DEF_ProcessAccessSignalling_Arg_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ProcessAccessSignalling_Arg_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* an-APDU */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 5, 0, 0 }, /* extensionContainer */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* selectedUMTS-Algorithms */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* selectedGSM-Algorithm */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* chosenRadioResourceInformation */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* selectedRab-Id */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 6, 0, 0 }, /* iUSelectedCodec */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 7, 0, 0 }, /* iuAvailableCodecsList */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 8, 0, 0 }, /* aoipSelectedCodecTarget */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 9, 0, 0 } /* aoipAvailableCodecsListMap */
};
static asn_SEQUENCE_specifics_t asn_SPC_ProcessAccessSignalling_Arg_specs_1 = {
	sizeof(struct ProcessAccessSignalling_Arg),
	offsetof(struct ProcessAccessSignalling_Arg, _asn_ctx),
	asn_MAP_ProcessAccessSignalling_Arg_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	11	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ProcessAccessSignalling_Arg = {
	"ProcessAccessSignalling-Arg",
	"ProcessAccessSignalling-Arg",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ProcessAccessSignalling_Arg_tags_1,
	sizeof(asn_DEF_ProcessAccessSignalling_Arg_tags_1)
		/sizeof(asn_DEF_ProcessAccessSignalling_Arg_tags_1[0]) - 1, /* 1 */
	asn_DEF_ProcessAccessSignalling_Arg_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProcessAccessSignalling_Arg_tags_1)
		/sizeof(asn_DEF_ProcessAccessSignalling_Arg_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_ProcessAccessSignalling_Arg_1,
	10,	/* Elements count */
	&asn_SPC_ProcessAccessSignalling_Arg_specs_1	/* Additional specs */
};

