/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=all`
 */

#ifndef	_ProvideSIWFSNumberRes_H_
#define	_ProvideSIWFSNumberRes_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ISDN-AddressString.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExtensionContainer;

/* ProvideSIWFSNumberRes */
typedef struct ProvideSIWFSNumberRes {
	ISDN_AddressString_t	 sIWFSNumber;
	struct ExtensionContainer	*extensionContainer	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProvideSIWFSNumberRes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProvideSIWFSNumberRes;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExtensionContainer.h"

#endif	/* _ProvideSIWFSNumberRes_H_ */
#include <asn_internal.h>
