/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=all`
 */

#ifndef	_ProvideSIWFSNumberArg_H_
#define	_ProvideSIWFSNumberArg_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ExternalSignalInfo.h"
#include "CallDirection.h"
#include "ISDN-AddressString.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExternalSignalInfo;
struct ExtensionContainer;

/* ProvideSIWFSNumberArg */
typedef struct ProvideSIWFSNumberArg {
	ExternalSignalInfo_t	 gsm_BearerCapability;
	ExternalSignalInfo_t	 isdn_BearerCapability;
	CallDirection_t	 call_Direction;
	ISDN_AddressString_t	 b_Subscriber_Address;
	ExternalSignalInfo_t	 chosenChannel;
	struct ExternalSignalInfo	*lowerLayerCompatibility	/* OPTIONAL */;
	struct ExternalSignalInfo	*highLayerCompatibility	/* OPTIONAL */;
	struct ExtensionContainer	*extensionContainer	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProvideSIWFSNumberArg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProvideSIWFSNumberArg;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExternalSignalInfo.h"
#include "ExtensionContainer.h"

#endif	/* _ProvideSIWFSNumberArg_H_ */
#include <asn_internal.h>
