/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=all`
 */

#include "PurgeMSArgV2.h"

static asn_TYPE_member_t asn_MBR_PurgeMSArgV2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PurgeMSArgV2, imsi),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_IMSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"imsi"
		},
	{ ATF_POINTER, 1, offsetof(struct PurgeMSArgV2, vlr_Number),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_ISDN_AddressString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vlr-Number"
		},
};
static const ber_tlv_tag_t asn_DEF_PurgeMSArgV2_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PurgeMSArgV2_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 1 }, /* imsi */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, -1, 0 } /* vlr-Number */
};
static asn_SEQUENCE_specifics_t asn_SPC_PurgeMSArgV2_specs_1 = {
	sizeof(struct PurgeMSArgV2),
	offsetof(struct PurgeMSArgV2, _asn_ctx),
	asn_MAP_PurgeMSArgV2_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PurgeMSArgV2 = {
	"PurgeMSArgV2",
	"PurgeMSArgV2",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PurgeMSArgV2_tags_1,
	sizeof(asn_DEF_PurgeMSArgV2_tags_1)
		/sizeof(asn_DEF_PurgeMSArgV2_tags_1[0]), /* 1 */
	asn_DEF_PurgeMSArgV2_tags_1,	/* Same as above */
	sizeof(asn_DEF_PurgeMSArgV2_tags_1)
		/sizeof(asn_DEF_PurgeMSArgV2_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PurgeMSArgV2_1,
	2,	/* Elements count */
	&asn_SPC_PurgeMSArgV2_specs_1	/* Additional specs */
};

