/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-CH-DataTypes"
 * 	found in "MAP-CH-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#ifndef	_RemoteUserFreeRes_H_
#define	_RemoteUserFreeRes_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RUF-Outcome.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExtensionContainer;

/* RemoteUserFreeRes */
typedef struct RemoteUserFreeRes {
	RUF_Outcome_t	 ruf_Outcome;
	struct ExtensionContainer	*extensionContainer	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RemoteUserFreeRes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RemoteUserFreeRes;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExtensionContainer.h"

#endif	/* _RemoteUserFreeRes_H_ */
#include <asn_internal.h>
