/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=all`
 */

#include "SendRoutingInfoArgV2.h"

static asn_TYPE_member_t asn_MBR_SendRoutingInfoArgV2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SendRoutingInfoArgV2, msisdn),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ISDN_AddressString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msisdn"
		},
	{ ATF_POINTER, 3, offsetof(struct SendRoutingInfoArgV2, cug_CheckInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CUG_CheckInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cug-CheckInfo"
		},
	{ ATF_POINTER, 2, offsetof(struct SendRoutingInfoArgV2, numberOfForwarding),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NumberOfForwarding,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfForwarding"
		},
	{ ATF_POINTER, 1, offsetof(struct SendRoutingInfoArgV2, networkSignalInfo),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExternalSignalInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"networkSignalInfo"
		},
};
static const ber_tlv_tag_t asn_DEF_SendRoutingInfoArgV2_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SendRoutingInfoArgV2_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* msisdn */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cug-CheckInfo */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* numberOfForwarding */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 3, 0, 0 } /* networkSignalInfo */
};
static asn_SEQUENCE_specifics_t asn_SPC_SendRoutingInfoArgV2_specs_1 = {
	sizeof(struct SendRoutingInfoArgV2),
	offsetof(struct SendRoutingInfoArgV2, _asn_ctx),
	asn_MAP_SendRoutingInfoArgV2_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SendRoutingInfoArgV2 = {
	"SendRoutingInfoArgV2",
	"SendRoutingInfoArgV2",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SendRoutingInfoArgV2_tags_1,
	sizeof(asn_DEF_SendRoutingInfoArgV2_tags_1)
		/sizeof(asn_DEF_SendRoutingInfoArgV2_tags_1[0]), /* 1 */
	asn_DEF_SendRoutingInfoArgV2_tags_1,	/* Same as above */
	sizeof(asn_DEF_SendRoutingInfoArgV2_tags_1)
		/sizeof(asn_DEF_SendRoutingInfoArgV2_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SendRoutingInfoArgV2_1,
	4,	/* Elements count */
	&asn_SPC_SendRoutingInfoArgV2_specs_1	/* Additional specs */
};

