/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=all`
 */

#ifndef	_SIWFSSignallingModifyArg_H_
#define	_SIWFSSignallingModifyArg_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExternalSignalInfo;
struct ExtensionContainer;

/* SIWFSSignallingModifyArg */
typedef struct SIWFSSignallingModifyArg {
	struct ExternalSignalInfo	*channelType	/* OPTIONAL */;
	struct ExternalSignalInfo	*chosenChannel	/* OPTIONAL */;
	struct ExtensionContainer	*extensionContainer	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SIWFSSignallingModifyArg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SIWFSSignallingModifyArg;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExternalSignalInfo.h"
#include "ExtensionContainer.h"

#endif	/* _SIWFSSignallingModifyArg_H_ */
#include <asn_internal.h>
