/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-SS-DataTypes"
 * 	found in "MAP-SS-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#include "SS-Data.h"

static asn_TYPE_member_t asn_MBR_SS_Data_1[] = {
	{ ATF_POINTER, 6, offsetof(struct SS_Data, ss_Code),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_SS_Code,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ss-Code"
		},
	{ ATF_POINTER, 5, offsetof(struct SS_Data, ss_Status),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SS_Status,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ss-Status"
		},
	{ ATF_POINTER, 4, offsetof(struct SS_Data, ss_SubscriptionOption),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_SS_SubscriptionOption,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ss-SubscriptionOption"
		},
	{ ATF_POINTER, 3, offsetof(struct SS_Data, basicServiceGroupList),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_BasicServiceGroupList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"basicServiceGroupList"
		},
	{ ATF_POINTER, 2, offsetof(struct SS_Data, defaultPriority),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_EMLPP_Priority,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"defaultPriority"
		},
	{ ATF_POINTER, 1, offsetof(struct SS_Data, nbrUser),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MC_Bearers,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nbrUser"
		},
};
static const ber_tlv_tag_t asn_DEF_SS_Data_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SS_Data_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, 0, 0 }, /* defaultPriority */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* ss-Code */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, 0, 0 }, /* basicServiceGroupList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* overrideCategory */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* cliRestrictionOption */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 }, /* ss-Status */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* nbrUser */
};
static asn_SEQUENCE_specifics_t asn_SPC_SS_Data_specs_1 = {
	sizeof(struct SS_Data),
	offsetof(struct SS_Data, _asn_ctx),
	asn_MAP_SS_Data_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SS_Data = {
	"SS-Data",
	"SS-Data",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SS_Data_tags_1,
	sizeof(asn_DEF_SS_Data_tags_1)
		/sizeof(asn_DEF_SS_Data_tags_1[0]), /* 1 */
	asn_DEF_SS_Data_tags_1,	/* Same as above */
	sizeof(asn_DEF_SS_Data_tags_1)
		/sizeof(asn_DEF_SS_Data_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SS_Data_1,
	6,	/* Elements count */
	&asn_SPC_SS_Data_specs_1	/* Additional specs */
};

