/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-OM-DataTypes"
 * 	found in "MAP-OM-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#include "TraceEventList.h"

static asn_TYPE_member_t asn_MBR_TraceEventList_1[] = {
	{ ATF_POINTER, 8, offsetof(struct TraceEventList, msc_s_List),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MSC_S_EventList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msc-s-List"
		},
	{ ATF_POINTER, 7, offsetof(struct TraceEventList, mgw_List),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MGW_EventList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mgw-List"
		},
	{ ATF_POINTER, 6, offsetof(struct TraceEventList, sgsn_List),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SGSN_EventList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sgsn-List"
		},
	{ ATF_POINTER, 5, offsetof(struct TraceEventList, ggsn_List),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GGSN_EventList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ggsn-List"
		},
	{ ATF_POINTER, 4, offsetof(struct TraceEventList, bmsc_List),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BMSC_EventList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bmsc-List"
		},
	{ ATF_POINTER, 3, offsetof(struct TraceEventList, mme_List),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MME_EventList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mme-List"
		},
	{ ATF_POINTER, 2, offsetof(struct TraceEventList, sgw_List),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SGW_EventList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sgw-List"
		},
	{ ATF_POINTER, 1, offsetof(struct TraceEventList, pgw_List),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PGW_EventList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"pgw-List"
		},
};
static const ber_tlv_tag_t asn_DEF_TraceEventList_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TraceEventList_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* msc-s-List */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* mgw-List */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sgsn-List */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ggsn-List */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* bmsc-List */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* mme-List */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* sgw-List */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* pgw-List */
};
static asn_SEQUENCE_specifics_t asn_SPC_TraceEventList_specs_1 = {
	sizeof(struct TraceEventList),
	offsetof(struct TraceEventList, _asn_ctx),
	asn_MAP_TraceEventList_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* Start extensions */
	9	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TraceEventList = {
	"TraceEventList",
	"TraceEventList",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TraceEventList_tags_1,
	sizeof(asn_DEF_TraceEventList_tags_1)
		/sizeof(asn_DEF_TraceEventList_tags_1[0]), /* 1 */
	asn_DEF_TraceEventList_tags_1,	/* Same as above */
	sizeof(asn_DEF_TraceEventList_tags_1)
		/sizeof(asn_DEF_TraceEventList_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TraceEventList_1,
	8,	/* Elements count */
	&asn_SPC_TraceEventList_specs_1	/* Additional specs */
};

