/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=all`
 */

#ifndef	_TripletListold_H_
#define	_TripletListold_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AuthenticationTriplet_v2;

/* TripletListold */
typedef struct TripletListold {
	A_SEQUENCE_OF(struct AuthenticationTriplet_v2) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TripletListold_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TripletListold;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AuthenticationTriplet-v2.h"

#endif	/* _TripletListold_H_ */
#include <asn_internal.h>
