/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-ER-DataTypes"
 * 	found in "MAP-ER-DataTypes.asn"
 * 	`asn1c -pdu=all`
 */

#include "UnknownSubscriberParam.h"

static asn_TYPE_member_t asn_MBR_UnknownSubscriberParam_1[] = {
	{ ATF_POINTER, 2, offsetof(struct UnknownSubscriberParam, extensionContainer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
	{ ATF_POINTER, 1, offsetof(struct UnknownSubscriberParam, unknownSubscriberDiagnostic),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_UnknownSubscriberDiagnostic,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"unknownSubscriberDiagnostic"
		},
};
static const ber_tlv_tag_t asn_DEF_UnknownSubscriberParam_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UnknownSubscriberParam_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 1, 0, 0 }, /* unknownSubscriberDiagnostic */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* extensionContainer */
};
static asn_SEQUENCE_specifics_t asn_SPC_UnknownSubscriberParam_specs_1 = {
	sizeof(struct UnknownSubscriberParam),
	offsetof(struct UnknownSubscriberParam, _asn_ctx),
	asn_MAP_UnknownSubscriberParam_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	0,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_UnknownSubscriberParam = {
	"UnknownSubscriberParam",
	"UnknownSubscriberParam",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_UnknownSubscriberParam_tags_1,
	sizeof(asn_DEF_UnknownSubscriberParam_tags_1)
		/sizeof(asn_DEF_UnknownSubscriberParam_tags_1[0]), /* 1 */
	asn_DEF_UnknownSubscriberParam_tags_1,	/* Same as above */
	sizeof(asn_DEF_UnknownSubscriberParam_tags_1)
		/sizeof(asn_DEF_UnknownSubscriberParam_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_UnknownSubscriberParam_1,
	2,	/* Elements count */
	&asn_SPC_UnknownSubscriberParam_specs_1	/* Additional specs */
};

