//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Ray.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_RAYTYPE                     129
#define IDR_WIZBAR                      130
#define ID_RENDERSCENE                  132
#define IDD_PLAY                        133
#define ID_TRACE                        1005
#define ID_IMAGE                        1006
#define ID_TIME                         1007
#define ID_PLAYBACK                     1009
#define ID_IMAGEPLAY                    1010
#define IDC_FROM                        1011
#define IDC_FROMX                       1012
#define IDC_FROMY                       1013
#define IDC_FROMZ                       1014
#define IDC_AT                          1015
#define IDC_ATX                         1016
#define IDC_ATY                         1017
#define IDC_ATZ                         1018
#define IDC_UPX                         1019
#define IDC_UPY                         1020
#define IDC_UPZ                         1021
#define IDC_UP                          1022
#define ID_SCENE                        32771
#define ID_RECTANGLE                    32772
#define ID_TRIANGLE                     32773
#define ID_ELLIPSOID                    32775
#define ID_CYLINDER                     32776
#define ID_POINTLIGHT                   32777
#define ID_DIRECTEDLIGHT                32778
#define ID_CONELIGHT                    32779
#define ID_RENDER                       32780
#define ID_SPHERE                       32781
#define ID_PLAY                         32782
#define ID_WATER                        32784
#define ID_CLOUDS                       32785
#define ID_HORIZON                      32786
#define ID_MARBLE                       32787
#define IDM_CLOUDMACRO                  32788
#define IDM_TERRAINMACRO                32789
#define IDM_MAKROPUTAR                  32790

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
