static_analyzer: static_analyzer0 static_analyzer1

static_analyzer0: static_analyzer0.c
	gcc -Wall -Werror -ggdb3 -fanalyzer static_analyzer0.c -o static_analyzer0

static_analyzer1: static_analyzer1.c
	gcc -Wall -Werror -ggdb3 -fanalyzer static_analyzer1.c -o static_analyzer1

