/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-set.m2c
 */
#ifndef CISCOLS1010MODULETABLE_DATA_SET_H
#define CISCOLS1010MODULETABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ciscoLS1010ModuleTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * CISCO-RHINO-MIB::ciscoLS1010ModuleTable is subid 1 of ciscoLS1010ModuleGroup.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.9.5.11.1.2.1, length: 12
*/


int ciscoLS1010ModuleTable_undo_setup( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx);
int ciscoLS1010ModuleTable_undo_cleanup( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx);
int ciscoLS1010ModuleTable_undo( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx);
int ciscoLS1010ModuleTable_commit( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx);
int ciscoLS1010ModuleTable_undo_commit( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx);


int ciscoLS1010ModuleType_check_value( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, u_long ciscoLS1010ModuleType_val);
int ciscoLS1010ModuleType_undo_setup( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );
int ciscoLS1010ModuleType_set( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, u_long ciscoLS1010ModuleType_val );
int ciscoLS1010ModuleType_undo( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );

int ciscoLS1010ModuleSerialNumber_check_value( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, long ciscoLS1010ModuleSerialNumber_val);
int ciscoLS1010ModuleSerialNumber_undo_setup( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );
int ciscoLS1010ModuleSerialNumber_set( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, long ciscoLS1010ModuleSerialNumber_val );
int ciscoLS1010ModuleSerialNumber_undo( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );

int ciscoLS1010ModuleHwVersion_check_value( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, long ciscoLS1010ModuleHwVersion_val);
int ciscoLS1010ModuleHwVersion_undo_setup( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );
int ciscoLS1010ModuleHwVersion_set( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, long ciscoLS1010ModuleHwVersion_val );
int ciscoLS1010ModuleHwVersion_undo( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );

int ciscoLS1010ModuleSwVersion_check_value( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, long ciscoLS1010ModuleSwVersion_val);
int ciscoLS1010ModuleSwVersion_undo_setup( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );
int ciscoLS1010ModuleSwVersion_set( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, long ciscoLS1010ModuleSwVersion_val );
int ciscoLS1010ModuleSwVersion_undo( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );

int ciscoLS1010ModuleDescr_check_value( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, char *ciscoLS1010ModuleDescr_val_ptr,  size_t ciscoLS1010ModuleDescr_val_ptr_len);
int ciscoLS1010ModuleDescr_undo_setup( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );
int ciscoLS1010ModuleDescr_set( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, char *ciscoLS1010ModuleDescr_val_ptr,  size_t ciscoLS1010ModuleDescr_val_ptr_len );
int ciscoLS1010ModuleDescr_undo( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );

int ciscoLS1010ModuleNumSubModules_check_value( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, long ciscoLS1010ModuleNumSubModules_val);
int ciscoLS1010ModuleNumSubModules_undo_setup( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );
int ciscoLS1010ModuleNumSubModules_set( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, long ciscoLS1010ModuleNumSubModules_val );
int ciscoLS1010ModuleNumSubModules_undo( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );

int ciscoLS1010ModuleAdminStatus_check_value( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, u_long ciscoLS1010ModuleAdminStatus_val);
int ciscoLS1010ModuleAdminStatus_undo_setup( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );
int ciscoLS1010ModuleAdminStatus_set( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, u_long ciscoLS1010ModuleAdminStatus_val );
int ciscoLS1010ModuleAdminStatus_undo( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );

int ciscoLS1010ModuleOperStatus_check_value( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, u_long ciscoLS1010ModuleOperStatus_val);
int ciscoLS1010ModuleOperStatus_undo_setup( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );
int ciscoLS1010ModuleOperStatus_set( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, u_long ciscoLS1010ModuleOperStatus_val );
int ciscoLS1010ModuleOperStatus_undo( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );

int ciscoLS1010ModuleHwVersionMinor_check_value( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, u_long ciscoLS1010ModuleHwVersionMinor_val);
int ciscoLS1010ModuleHwVersionMinor_undo_setup( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );
int ciscoLS1010ModuleHwVersionMinor_set( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, u_long ciscoLS1010ModuleHwVersionMinor_val );
int ciscoLS1010ModuleHwVersionMinor_undo( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );

int ciscoLS1010ModuleSerialNumberString_check_value( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, char *ciscoLS1010ModuleSerialNumberString_val_ptr,  size_t ciscoLS1010ModuleSerialNumberString_val_ptr_len);
int ciscoLS1010ModuleSerialNumberString_undo_setup( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );
int ciscoLS1010ModuleSerialNumberString_set( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, char *ciscoLS1010ModuleSerialNumberString_val_ptr,  size_t ciscoLS1010ModuleSerialNumberString_val_ptr_len );
int ciscoLS1010ModuleSerialNumberString_undo( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx );


int ciscoLS1010ModuleTable_check_dependencies(ciscoLS1010ModuleTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* CISCOLS1010MODULETABLE_DATA_SET_H */
