/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef CISCOLS1010MODULETABLE_INTERFACE_H
#define CISCOLS1010MODULETABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "ciscoLS1010ModuleTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _ciscoLS1010ModuleTable_initialize_interface(ciscoLS1010ModuleTable_registration * user_ctx,
                                    u_long flags);
void _ciscoLS1010ModuleTable_shutdown_interface(ciscoLS1010ModuleTable_registration * user_ctx);

ciscoLS1010ModuleTable_registration *
ciscoLS1010ModuleTable_registration_get( void );

ciscoLS1010ModuleTable_registration *
ciscoLS1010ModuleTable_registration_set( ciscoLS1010ModuleTable_registration * newreg );

netsnmp_container *ciscoLS1010ModuleTable_container_get( void );
int ciscoLS1010ModuleTable_container_size( void );

u_int ciscoLS1010ModuleTable_dirty_get( void );
void ciscoLS1010ModuleTable_dirty_set( u_int status );

    ciscoLS1010ModuleTable_rowreq_ctx * ciscoLS1010ModuleTable_allocate_rowreq_ctx(void *);
void ciscoLS1010ModuleTable_release_rowreq_ctx(ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx);

int ciscoLS1010ModuleTable_index_to_oid(netsnmp_index *oid_idx,
                            ciscoLS1010ModuleTable_mib_index *mib_idx);
int ciscoLS1010ModuleTable_index_from_oid(netsnmp_index *oid_idx,
                              ciscoLS1010ModuleTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void ciscoLS1010ModuleTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* CISCOLS1010MODULETABLE_INTERFACE_H */
/** @} */
