/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "ciscoLS1010ModuleTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement ciscoLS1010ModuleTable get routines.
 * TODO:240:M: Implement ciscoLS1010ModuleTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ciscoLS1010ModuleTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * CISCO-RHINO-MIB::ciscoLS1010ModuleTable is subid 1 of ciscoLS1010ModuleGroup.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.9.5.11.1.2.1, length: 12
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement ciscoLS1010ModuleTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param ciscoLS1010ModuleIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
ciscoLS1010ModuleTable_indexes_set_tbl_idx(ciscoLS1010ModuleTable_mib_index *tbl_idx, long ciscoLS1010ModuleIndex_val)
{
    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleTable_indexes_set_tbl_idx","called\n"));

    /* ciscoLS1010ModuleIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/a/w/e/R/d/h */
    tbl_idx->ciscoLS1010ModuleIndex = ciscoLS1010ModuleIndex_val;
    

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
ciscoLS1010ModuleTable_indexes_set(ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, long ciscoLS1010ModuleIndex_val)
{
    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleTable_indexes_set","called\n"));

    if(MFD_SUCCESS != ciscoLS1010ModuleTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , ciscoLS1010ModuleIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != ciscoLS1010ModuleTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleTable_indexes_set */


/*---------------------------------------------------------------------
 * CISCO-RHINO-MIB::ciscoLS1010ModuleEntry.ciscoLS1010ModuleType
 * ciscoLS1010ModuleType is subid 2 of ciscoLS1010ModuleEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.9.5.11.1.2.1.1.2
 * Description:
The type of module.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 10/16. Values:  other(1), carrier(2), cpuSwitchAndFeature(3), cpuSwitchAndFeaturePFQ(4), superCarrier(5), cpuRoute(6), switch10GAndFC(7), switch10GNoFC(8), atmFabricIntegration(9), dualSlot(10), cmpmCarrier(11), tsCarrier(12), nodeSwitchProcessor2ndGeneration(13)
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the ciscoLS1010ModuleType data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ciscoLS1010ModuleType_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ciscoLS1010ModuleType_get( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, u_long * ciscoLS1010ModuleType_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ciscoLS1010ModuleType_val_ptr );


    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleType_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ciscoLS1010ModuleType data.
 * copy (* ciscoLS1010ModuleType_val_ptr ) from rowreq_ctx->data
 */
    (* ciscoLS1010ModuleType_val_ptr ) = rowreq_ctx->data.ciscoLS1010ModuleType;

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleType_get */

/*---------------------------------------------------------------------
 * CISCO-RHINO-MIB::ciscoLS1010ModuleEntry.ciscoLS1010ModuleSerialNumber
 * ciscoLS1010ModuleSerialNumber is subid 3 of ciscoLS1010ModuleEntry.
 * Its status is Deprecated, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.9.5.11.1.2.1.1.3
 * Description:
The serial number of the module.
                       Deprecated in favor of object 
                       ciscoLS1010ModuleSerialNumberString. This object
                       returns 0 for modules using an alphanumeric 
                       numbering scheme.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the ciscoLS1010ModuleSerialNumber data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ciscoLS1010ModuleSerialNumber_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ciscoLS1010ModuleSerialNumber_get( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, long * ciscoLS1010ModuleSerialNumber_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ciscoLS1010ModuleSerialNumber_val_ptr );


    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleSerialNumber_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ciscoLS1010ModuleSerialNumber data.
 * copy (* ciscoLS1010ModuleSerialNumber_val_ptr ) from rowreq_ctx->data
 */
    (* ciscoLS1010ModuleSerialNumber_val_ptr ) = rowreq_ctx->data.ciscoLS1010ModuleSerialNumber;

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleSerialNumber_get */

/*---------------------------------------------------------------------
 * CISCO-RHINO-MIB::ciscoLS1010ModuleEntry.ciscoLS1010ModuleHwVersion
 * ciscoLS1010ModuleHwVersion is subid 4 of ciscoLS1010ModuleEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.9.5.11.1.2.1.1.4
 * Description:
The hardware version of the module.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the ciscoLS1010ModuleHwVersion data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ciscoLS1010ModuleHwVersion_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ciscoLS1010ModuleHwVersion_get( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, long * ciscoLS1010ModuleHwVersion_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ciscoLS1010ModuleHwVersion_val_ptr );


    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleHwVersion_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ciscoLS1010ModuleHwVersion data.
 * copy (* ciscoLS1010ModuleHwVersion_val_ptr ) from rowreq_ctx->data
 */
    (* ciscoLS1010ModuleHwVersion_val_ptr ) = rowreq_ctx->data.ciscoLS1010ModuleHwVersion;

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleHwVersion_get */

/*---------------------------------------------------------------------
 * CISCO-RHINO-MIB::ciscoLS1010ModuleEntry.ciscoLS1010ModuleSwVersion
 * ciscoLS1010ModuleSwVersion is subid 5 of ciscoLS1010ModuleEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.9.5.11.1.2.1.1.5
 * Description:
The software version number.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the ciscoLS1010ModuleSwVersion data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ciscoLS1010ModuleSwVersion_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ciscoLS1010ModuleSwVersion_get( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, long * ciscoLS1010ModuleSwVersion_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ciscoLS1010ModuleSwVersion_val_ptr );


    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleSwVersion_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ciscoLS1010ModuleSwVersion data.
 * copy (* ciscoLS1010ModuleSwVersion_val_ptr ) from rowreq_ctx->data
 */
    (* ciscoLS1010ModuleSwVersion_val_ptr ) = rowreq_ctx->data.ciscoLS1010ModuleSwVersion;

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleSwVersion_get */

/*---------------------------------------------------------------------
 * CISCO-RHINO-MIB::ciscoLS1010ModuleEntry.ciscoLS1010ModuleDescr
 * ciscoLS1010ModuleDescr is subid 6 of ciscoLS1010ModuleEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.9.5.11.1.2.1.1.6
 * Description:
A descriptive string used by the agent 
                      to describe the module.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Extract the current value of the ciscoLS1010ModuleDescr data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ciscoLS1010ModuleDescr_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param ciscoLS1010ModuleDescr_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by ciscoLS1010ModuleDescr.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*ciscoLS1010ModuleDescr_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update ciscoLS1010ModuleDescr_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
ciscoLS1010ModuleDescr_get( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, char **ciscoLS1010ModuleDescr_val_ptr_ptr, size_t *ciscoLS1010ModuleDescr_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != ciscoLS1010ModuleDescr_val_ptr_ptr) && (NULL != *ciscoLS1010ModuleDescr_val_ptr_ptr));
   netsnmp_assert( NULL != ciscoLS1010ModuleDescr_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleDescr_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ciscoLS1010ModuleDescr data.
 * copy (* ciscoLS1010ModuleDescr_val_ptr_ptr ) data and (* ciscoLS1010ModuleDescr_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for ciscoLS1010ModuleDescr data
     */
    if ((NULL == (* ciscoLS1010ModuleDescr_val_ptr_ptr )) ||
        ((* ciscoLS1010ModuleDescr_val_ptr_len_ptr ) <
         (rowreq_ctx->data.ciscoLS1010ModuleDescr_len* sizeof(rowreq_ctx->data.ciscoLS1010ModuleDescr[0])))) {
        /*
         * allocate space for ciscoLS1010ModuleDescr data
         */
        (* ciscoLS1010ModuleDescr_val_ptr_ptr ) = malloc(rowreq_ctx->data.ciscoLS1010ModuleDescr_len* sizeof(rowreq_ctx->data.ciscoLS1010ModuleDescr[0]));
        if(NULL == (* ciscoLS1010ModuleDescr_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.ciscoLS1010ModuleDescr)\n");
            return MFD_ERROR;
        }
    }
    (* ciscoLS1010ModuleDescr_val_ptr_len_ptr ) = rowreq_ctx->data.ciscoLS1010ModuleDescr_len* sizeof(rowreq_ctx->data.ciscoLS1010ModuleDescr[0]);
    memcpy( (* ciscoLS1010ModuleDescr_val_ptr_ptr ), rowreq_ctx->data.ciscoLS1010ModuleDescr, rowreq_ctx->data.ciscoLS1010ModuleDescr_len* sizeof(rowreq_ctx->data.ciscoLS1010ModuleDescr[0]) );

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleDescr_get */

/*---------------------------------------------------------------------
 * CISCO-RHINO-MIB::ciscoLS1010ModuleEntry.ciscoLS1010ModuleNumSubModules
 * ciscoLS1010ModuleNumSubModules is subid 7 of ciscoLS1010ModuleEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.9.5.11.1.2.1.1.7
 * Description:
The max number of sub-modules supported by this module.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the ciscoLS1010ModuleNumSubModules data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ciscoLS1010ModuleNumSubModules_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ciscoLS1010ModuleNumSubModules_get( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, long * ciscoLS1010ModuleNumSubModules_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ciscoLS1010ModuleNumSubModules_val_ptr );


    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleNumSubModules_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ciscoLS1010ModuleNumSubModules data.
 * copy (* ciscoLS1010ModuleNumSubModules_val_ptr ) from rowreq_ctx->data
 */
    (* ciscoLS1010ModuleNumSubModules_val_ptr ) = rowreq_ctx->data.ciscoLS1010ModuleNumSubModules;

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleNumSubModules_get */

/*---------------------------------------------------------------------
 * CISCO-RHINO-MIB::ciscoLS1010ModuleEntry.ciscoLS1010ModuleAdminStatus
 * ciscoLS1010ModuleAdminStatus is subid 8 of ciscoLS1010ModuleEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.9.5.11.1.2.1.1.8
 * Description:
This object, when read, always returns a value of
                      ok(1).  Setting this object to one of the
                      acceptable values gives the following results:
                          reset:   reset the module's control logic
                          enable:  enable the module
                          disable: disable the module
                      Setting this object to any other values results in 
                      an error.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  enable(1), disable(2), reset(3)
 *
 * Its syntax is AdminStatus (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the ciscoLS1010ModuleAdminStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ciscoLS1010ModuleAdminStatus_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ciscoLS1010ModuleAdminStatus_get( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, u_long * ciscoLS1010ModuleAdminStatus_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ciscoLS1010ModuleAdminStatus_val_ptr );


    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleAdminStatus_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ciscoLS1010ModuleAdminStatus data.
 * copy (* ciscoLS1010ModuleAdminStatus_val_ptr ) from rowreq_ctx->data
 */
    (* ciscoLS1010ModuleAdminStatus_val_ptr ) = rowreq_ctx->data.ciscoLS1010ModuleAdminStatus;

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleAdminStatus_get */

/*---------------------------------------------------------------------
 * CISCO-RHINO-MIB::ciscoLS1010ModuleEntry.ciscoLS1010ModuleOperStatus
 * ciscoLS1010ModuleOperStatus is subid 9 of ciscoLS1010ModuleEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.9.5.11.1.2.1.1.9
 * Description:
Operational status of the module.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 4/8. Values:  unknown(1), ok(2), fault(3), fanAlarm(4), partialFault(5), empty(6)
 *
 * Its syntax is OperStatus (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the ciscoLS1010ModuleOperStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ciscoLS1010ModuleOperStatus_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ciscoLS1010ModuleOperStatus_get( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, u_long * ciscoLS1010ModuleOperStatus_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ciscoLS1010ModuleOperStatus_val_ptr );


    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleOperStatus_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ciscoLS1010ModuleOperStatus data.
 * copy (* ciscoLS1010ModuleOperStatus_val_ptr ) from rowreq_ctx->data
 */
    (* ciscoLS1010ModuleOperStatus_val_ptr ) = rowreq_ctx->data.ciscoLS1010ModuleOperStatus;

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleOperStatus_get */

/*---------------------------------------------------------------------
 * CISCO-RHINO-MIB::ciscoLS1010ModuleEntry.ciscoLS1010ModuleHwVersionMinor
 * ciscoLS1010ModuleHwVersionMinor is subid 10 of ciscoLS1010ModuleEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.9.5.11.1.2.1.1.10
 * Description:
The minor hardware version of the module.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the ciscoLS1010ModuleHwVersionMinor data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ciscoLS1010ModuleHwVersionMinor_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
ciscoLS1010ModuleHwVersionMinor_get( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, u_long * ciscoLS1010ModuleHwVersionMinor_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != ciscoLS1010ModuleHwVersionMinor_val_ptr );


    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleHwVersionMinor_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ciscoLS1010ModuleHwVersionMinor data.
 * copy (* ciscoLS1010ModuleHwVersionMinor_val_ptr ) from rowreq_ctx->data
 */
    (* ciscoLS1010ModuleHwVersionMinor_val_ptr ) = rowreq_ctx->data.ciscoLS1010ModuleHwVersionMinor;

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleHwVersionMinor_get */

/*---------------------------------------------------------------------
 * CISCO-RHINO-MIB::ciscoLS1010ModuleEntry.ciscoLS1010ModuleSerialNumberString
 * ciscoLS1010ModuleSerialNumberString is subid 11 of ciscoLS1010ModuleEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.9.5.11.1.2.1.1.11
 * Description:
The serial number of the module.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Extract the current value of the ciscoLS1010ModuleSerialNumberString data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param ciscoLS1010ModuleSerialNumberString_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param ciscoLS1010ModuleSerialNumberString_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by ciscoLS1010ModuleSerialNumberString.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*ciscoLS1010ModuleSerialNumberString_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update ciscoLS1010ModuleSerialNumberString_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
ciscoLS1010ModuleSerialNumberString_get( ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx, char **ciscoLS1010ModuleSerialNumberString_val_ptr_ptr, size_t *ciscoLS1010ModuleSerialNumberString_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != ciscoLS1010ModuleSerialNumberString_val_ptr_ptr) && (NULL != *ciscoLS1010ModuleSerialNumberString_val_ptr_ptr));
   netsnmp_assert( NULL != ciscoLS1010ModuleSerialNumberString_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleSerialNumberString_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the ciscoLS1010ModuleSerialNumberString data.
 * copy (* ciscoLS1010ModuleSerialNumberString_val_ptr_ptr ) data and (* ciscoLS1010ModuleSerialNumberString_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for ciscoLS1010ModuleSerialNumberString data
     */
    if ((NULL == (* ciscoLS1010ModuleSerialNumberString_val_ptr_ptr )) ||
        ((* ciscoLS1010ModuleSerialNumberString_val_ptr_len_ptr ) <
         (rowreq_ctx->data.ciscoLS1010ModuleSerialNumberString_len* sizeof(rowreq_ctx->data.ciscoLS1010ModuleSerialNumberString[0])))) {
        /*
         * allocate space for ciscoLS1010ModuleSerialNumberString data
         */
        (* ciscoLS1010ModuleSerialNumberString_val_ptr_ptr ) = malloc(rowreq_ctx->data.ciscoLS1010ModuleSerialNumberString_len* sizeof(rowreq_ctx->data.ciscoLS1010ModuleSerialNumberString[0]));
        if(NULL == (* ciscoLS1010ModuleSerialNumberString_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.ciscoLS1010ModuleSerialNumberString)\n");
            return MFD_ERROR;
        }
    }
    (* ciscoLS1010ModuleSerialNumberString_val_ptr_len_ptr ) = rowreq_ctx->data.ciscoLS1010ModuleSerialNumberString_len* sizeof(rowreq_ctx->data.ciscoLS1010ModuleSerialNumberString[0]);
    memcpy( (* ciscoLS1010ModuleSerialNumberString_val_ptr_ptr ), rowreq_ctx->data.ciscoLS1010ModuleSerialNumberString, rowreq_ctx->data.ciscoLS1010ModuleSerialNumberString_len* sizeof(rowreq_ctx->data.ciscoLS1010ModuleSerialNumberString[0]) );

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleSerialNumberString_get */



/** @} */
