/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
/** \page MFD helper for ciscoLS1010ModuleTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "ciscoLS1010ModuleTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "ciscoLS1010ModuleTable_interface.h"

const oid ciscoLS1010ModuleTable_oid[] = { CISCOLS1010MODULETABLE_OID };
const int ciscoLS1010ModuleTable_oid_size = OID_LENGTH(ciscoLS1010ModuleTable_oid);

    ciscoLS1010ModuleTable_registration  ciscoLS1010ModuleTable_user_context;

void initialize_table_ciscoLS1010ModuleTable(void);
void shutdown_table_ciscoLS1010ModuleTable(void);


/**
 * Initializes the ciscoLS1010ModuleTable module
 */
void
init_ciscoLS1010ModuleTable(void)
{
    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:init_ciscoLS1010ModuleTable","called\n"));

    /*
     * TODO:300:o: Perform ciscoLS1010ModuleTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("ciscoLS1010ModuleTable"))
        initialize_table_ciscoLS1010ModuleTable();

} /* init_ciscoLS1010ModuleTable */

/**
 * Shut-down the ciscoLS1010ModuleTable module (agent is exiting)
 */
void
shutdown_ciscoLS1010ModuleTable(void)
{
    if (should_init("ciscoLS1010ModuleTable"))
        shutdown_table_ciscoLS1010ModuleTable();

}

/**
 * Initialize the table ciscoLS1010ModuleTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_ciscoLS1010ModuleTable(void)
{
    ciscoLS1010ModuleTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:initialize_table_ciscoLS1010ModuleTable","called\n"));

    /*
     * TODO:301:o: Perform ciscoLS1010ModuleTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize ciscoLS1010ModuleTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("ciscoLS1010ModuleTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _ciscoLS1010ModuleTable_initialize_interface(user_context, flags);
} /* initialize_table_ciscoLS1010ModuleTable */

/**
 * Shutdown the table ciscoLS1010ModuleTable 
 */
void
shutdown_table_ciscoLS1010ModuleTable(void)
{
    /*
     * call interface shutdown code
     */
    _ciscoLS1010ModuleTable_shutdown_interface(&ciscoLS1010ModuleTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
ciscoLS1010ModuleTable_rowreq_ctx_init(ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra ciscoLS1010ModuleTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void ciscoLS1010ModuleTable_rowreq_ctx_cleanup(ciscoLS1010ModuleTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra ciscoLS1010ModuleTable rowreq cleanup.
     */
} /* ciscoLS1010ModuleTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
ciscoLS1010ModuleTable_pre_request(ciscoLS1010ModuleTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform ciscoLS1010ModuleTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
ciscoLS1010ModuleTable_post_request(ciscoLS1010ModuleTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:ciscoLS1010ModuleTable:ciscoLS1010ModuleTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform ciscoLS1010ModuleTable post-request actions.
     */

    /*
     * check to set if any rows were changed.
     */
    if (ciscoLS1010ModuleTable_dirty_get()) {
        /*
         * check if request was successful. If so, this would be
         * a good place to save data to its persistent store.
         */
        if (MFD_SUCCESS == rc) {
            /*
             * save changed rows, if you haven't already
             */
        }
        
        ciscoLS1010ModuleTable_dirty_set(0); /* clear table dirty flag */
    }

    return MFD_SUCCESS;
} /* ciscoLS1010ModuleTable_post_request */


/** @{ */
