/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.create-dataset.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "netSnmpIETFWGTable.h"
netsnmp_feature_require(table_set_multi_add_default_row)
netsnmp_feature_require(unregister_auto_data_table)
netsnmp_feature_require(delete_table_data_set)
netsnmp_feature_require(table_dataset)
netsnmp_feature_require(table_set_multi_add_default_row)
netsnmp_feature_require(table_dataset_unregister_auto_data_table)

netsnmp_table_data_set *table_set;

/** Initialize the netSnmpIETFWGTable table by defining its contents and how it's structured */
void
initialize_table_netSnmpIETFWGTable(void)
{
    const oid netSnmpIETFWGTable_oid[] = {1,3,6,1,4,1,8072,2,2,1};

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("netSnmpIETFWGTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_netSnmpIETFWGTable",
                "adding indexes to table netSnmpIETFWGTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_OCTET_STR,  /* index: nsIETFWGName */
                           0);

    DEBUGMSGTL(("initialize_table_netSnmpIETFWGTable",
                "adding column types to table netSnmpIETFWGTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_NSIETFWGNAME, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_NSIETFWGCHAIR1, ASN_OCTET_STR, 1,
                                            NULL, 0,
                                            COLUMN_NSIETFWGCHAIR2, ASN_OCTET_STR, 1,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change netSnmpIETFWGTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("netSnmpIETFWGTable", netSnmpIETFWGTable_handler,
                                                        netSnmpIETFWGTable_oid,
                                                        OID_LENGTH(netSnmpIETFWGTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);

    /*
     * create the a row for the table, and add the data 
     */
    row = netsnmp_create_table_data_row();    

    /*
     * set the index to the IETF WG name "snmpv3"
     */
    netsnmp_table_row_add_index(row, ASN_OCTET_STR, "snmpv3",
                                strlen("snmpv3"));

     /*
     * set column 2 to be the WG chair name "Russ Mundy"
     */
    netsnmp_set_row_column(row, 2, ASN_OCTET_STR,
                           "Russ Mundy", strlen("Russ Mundy"));

    netsnmp_mark_row_column_writable(row, 2, 1);        /* make writable via SETs */

    /*
     * set column 3 to be the WG chair name "David Harrington"
     */
    netsnmp_set_row_column(row, 3, ASN_OCTET_STR, "David Harrington",
                           strlen("David Harrington"));


    netsnmp_mark_row_column_writable(row, 3, 1);        /* make writable via SETs */

     /*
     * add the row to the table 
     */
    netsnmp_table_dataset_add_row(table_set, row);

    #ifdef ADD_MORE_DATA
    /*
     * add the data, for the second row
     */
    row = netsnmp_create_table_data_row();
    netsnmp_table_row_add_index(row, ASN_OCTET_STR, "snmpconf",
                                strlen("snmpconf"));
    netsnmp_set_row_column(row, 2, ASN_OCTET_STR, "David Partain",
                           strlen("David Partain"));
    netsnmp_mark_row_column_writable(row, 2, 1);        /* make writable */
    netsnmp_set_row_column(row, 3, ASN_OCTET_STR, "Jon Saperia",
                           strlen("Jon Saperia"));
    netsnmp_mark_row_column_writable(row, 3, 1);        /* make writable */
    netsnmp_table_dataset_add_row(table_set, row);
#endif

    /*
     * Finally, this actually allows the "add_row" token it the
     * * snmpd.conf file to add rows to this table.
     * * Example snmpd.conf line:
     * *   add_row netSnmpIETFWGTable eos "Glenn Waters" "Dale Francisco"
     */
    netsnmp_register_auto_data_table(table_set, NULL);

    DEBUGMSGTL(("example_data_set", "Done initializing.\n"));


}

/** Initializes the netSnmpIETFWGTable module */
void
init_netSnmpIETFWGTable(void)
{

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_netSnmpIETFWGTable();
}

/** handles requests for the netSnmpIETFWGTable table, if anything else needs to be done */
int
netSnmpIETFWGTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}
