/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#include "AnyTimeSubscriptionInterrogationRes.h"

static asn_TYPE_member_t asn_MBR_AnyTimeSubscriptionInterrogationRes_1[] = {
	{ ATF_POINTER, 11, offsetof(struct AnyTimeSubscriptionInterrogationRes, callForwardingData),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallForwardingData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callForwardingData"
		},
	{ ATF_POINTER, 10, offsetof(struct AnyTimeSubscriptionInterrogationRes, callBarringData),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallBarringData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callBarringData"
		},
	{ ATF_POINTER, 9, offsetof(struct AnyTimeSubscriptionInterrogationRes, odb_Info),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ODB_Info,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"odb-Info"
		},
	{ ATF_POINTER, 8, offsetof(struct AnyTimeSubscriptionInterrogationRes, camel_SubscriptionInfo),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CAMEL_SubscriptionInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"camel-SubscriptionInfo"
		},
	{ ATF_POINTER, 7, offsetof(struct AnyTimeSubscriptionInterrogationRes, supportedVLR_CAMEL_Phases),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SupportedCamelPhases,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"supportedVLR-CAMEL-Phases"
		},
	{ ATF_POINTER, 6, offsetof(struct AnyTimeSubscriptionInterrogationRes, supportedSGSN_CAMEL_Phases),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SupportedCamelPhases,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"supportedSGSN-CAMEL-Phases"
		},
	{ ATF_POINTER, 5, offsetof(struct AnyTimeSubscriptionInterrogationRes, extensionContainer),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
	{ ATF_POINTER, 4, offsetof(struct AnyTimeSubscriptionInterrogationRes, offeredCamel4CSIsInVLR),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OfferedCamel4CSIs,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"offeredCamel4CSIsInVLR"
		},
	{ ATF_POINTER, 3, offsetof(struct AnyTimeSubscriptionInterrogationRes, offeredCamel4CSIsInSGSN),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OfferedCamel4CSIs,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"offeredCamel4CSIsInSGSN"
		},
	{ ATF_POINTER, 2, offsetof(struct AnyTimeSubscriptionInterrogationRes, msisdn_BS_List),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MSISDN_BS_List,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msisdn-BS-List"
		},
	{ ATF_POINTER, 1, offsetof(struct AnyTimeSubscriptionInterrogationRes, csg_SubscriptionDataList),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSG_SubscriptionDataList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"csg-SubscriptionDataList"
		},
};
static const ber_tlv_tag_t asn_DEF_AnyTimeSubscriptionInterrogationRes_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AnyTimeSubscriptionInterrogationRes_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* callForwardingData */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* callBarringData */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* odb-Info */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* camel-SubscriptionInfo */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* supportedVLR-CAMEL-Phases */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* supportedSGSN-CAMEL-Phases */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* extensionContainer */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 7, 0, 0 }, /* offeredCamel4CSIsInVLR */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 8, 0, 0 }, /* offeredCamel4CSIsInSGSN */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 9, 0, 0 }, /* msisdn-BS-List */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 10, 0, 0 } /* csg-SubscriptionDataList */
};
static asn_SEQUENCE_specifics_t asn_SPC_AnyTimeSubscriptionInterrogationRes_specs_1 = {
	sizeof(struct AnyTimeSubscriptionInterrogationRes),
	offsetof(struct AnyTimeSubscriptionInterrogationRes, _asn_ctx),
	asn_MAP_AnyTimeSubscriptionInterrogationRes_tag2el_1,
	11,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	6,	/* Start extensions */
	12	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AnyTimeSubscriptionInterrogationRes = {
	"AnyTimeSubscriptionInterrogationRes",
	"AnyTimeSubscriptionInterrogationRes",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AnyTimeSubscriptionInterrogationRes_tags_1,
	sizeof(asn_DEF_AnyTimeSubscriptionInterrogationRes_tags_1)
		/sizeof(asn_DEF_AnyTimeSubscriptionInterrogationRes_tags_1[0]), /* 1 */
	asn_DEF_AnyTimeSubscriptionInterrogationRes_tags_1,	/* Same as above */
	sizeof(asn_DEF_AnyTimeSubscriptionInterrogationRes_tags_1)
		/sizeof(asn_DEF_AnyTimeSubscriptionInterrogationRes_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AnyTimeSubscriptionInterrogationRes_1,
	11,	/* Elements count */
	&asn_SPC_AnyTimeSubscriptionInterrogationRes_specs_1	/* Additional specs */
};

