/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_AnyTimeSubscriptionInterrogationRes_H_
#define	_AnyTimeSubscriptionInterrogationRes_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SupportedCamelPhases.h"
#include "OfferedCamel4CSIs.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CallForwardingData;
struct CallBarringData;
struct ODB_Info;
struct CAMEL_SubscriptionInfo;
struct ExtensionContainer;
struct MSISDN_BS_List;
struct CSG_SubscriptionDataList;

/* AnyTimeSubscriptionInterrogationRes */
typedef struct AnyTimeSubscriptionInterrogationRes {
	struct CallForwardingData	*callForwardingData	/* OPTIONAL */;
	struct CallBarringData	*callBarringData	/* OPTIONAL */;
	struct ODB_Info	*odb_Info	/* OPTIONAL */;
	struct CAMEL_SubscriptionInfo	*camel_SubscriptionInfo	/* OPTIONAL */;
	SupportedCamelPhases_t	*supportedVLR_CAMEL_Phases	/* OPTIONAL */;
	SupportedCamelPhases_t	*supportedSGSN_CAMEL_Phases	/* OPTIONAL */;
	struct ExtensionContainer	*extensionContainer	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	OfferedCamel4CSIs_t	*offeredCamel4CSIsInVLR	/* OPTIONAL */;
	OfferedCamel4CSIs_t	*offeredCamel4CSIsInSGSN	/* OPTIONAL */;
	struct MSISDN_BS_List	*msisdn_BS_List	/* OPTIONAL */;
	struct CSG_SubscriptionDataList	*csg_SubscriptionDataList	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AnyTimeSubscriptionInterrogationRes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AnyTimeSubscriptionInterrogationRes;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CallForwardingData.h"
#include "CallBarringData.h"
#include "ODB-Info.h"
#include "CAMEL-SubscriptionInfo.h"
#include "ExtensionContainer.h"
#include "MSISDN-BS-List.h"
#include "CSG-SubscriptionDataList.h"

#endif	/* _AnyTimeSubscriptionInterrogationRes_H_ */
#include <asn_internal.h>
