/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-CH-DataTypes"
 * 	found in "MAP-CH-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_CallReportData_H_
#define	_CallReportData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MonitoringMode.h"
#include "CallOutcome.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExtensionContainer;

/* CallReportData */
typedef struct CallReportData {
	MonitoringMode_t	*monitoringMode	/* OPTIONAL */;
	CallOutcome_t	*callOutcome	/* OPTIONAL */;
	struct ExtensionContainer	*extensionContainer	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CallReportData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallReportData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExtensionContainer.h"

#endif	/* _CallReportData_H_ */
#include <asn_internal.h>
