/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_CSG_SubscriptionData_H_
#define	_CSG_SubscriptionData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CSG-Id.h"
#include "Time.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExtensionContainer;

/* CSG-SubscriptionData */
typedef struct CSG_SubscriptionData {
	CSG_Id_t	 csg_Id;
	Time_t	*expirationDate	/* OPTIONAL */;
	struct ExtensionContainer	*extensionContainer	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CSG_SubscriptionData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CSG_SubscriptionData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExtensionContainer.h"

#endif	/* _CSG_SubscriptionData_H_ */
#include <asn_internal.h>
