/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_CurrentPassword_H_
#define	_CurrentPassword_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NumericString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CurrentPassword */
typedef NumericString_t	 CurrentPassword_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CurrentPassword;
asn_struct_free_f CurrentPassword_free;
asn_struct_print_f CurrentPassword_print;
asn_constr_check_f CurrentPassword_constraint;
ber_type_decoder_f CurrentPassword_decode_ber;
der_type_encoder_f CurrentPassword_encode_der;
xer_type_decoder_f CurrentPassword_decode_xer;
xer_type_encoder_f CurrentPassword_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CurrentPassword_H_ */
#include <asn_internal.h>
