/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#include "EPS-Info.h"

static asn_TYPE_member_t asn_MBR_EPS_Info_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EPS_Info, choice.pdn_gw_update),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDN_GW_Update,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"pdn-gw-update"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPS_Info, choice.isr_Information),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ISR_Information,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"isr-Information"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_EPS_Info_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pdn-gw-update */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* isr-Information */
};
static asn_CHOICE_specifics_t asn_SPC_EPS_Info_specs_1 = {
	sizeof(struct EPS_Info),
	offsetof(struct EPS_Info, _asn_ctx),
	offsetof(struct EPS_Info, present),
	sizeof(((struct EPS_Info *)0)->present),
	asn_MAP_EPS_Info_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_EPS_Info = {
	"EPS-Info",
	"EPS-Info",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_EPS_Info_1,
	2,	/* Elements count */
	&asn_SPC_EPS_Info_specs_1	/* Additional specs */
};

