/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#include "Ext-CallBarringInfoFor-CSE.h"

static asn_TYPE_member_t asn_MBR_Ext_CallBarringInfoFor_CSE_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Ext_CallBarringInfoFor_CSE, ss_Code),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SS_Code,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ss-Code"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Ext_CallBarringInfoFor_CSE, callBarringFeatureList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ext_CallBarFeatureList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callBarringFeatureList"
		},
	{ ATF_POINTER, 4, offsetof(struct Ext_CallBarringInfoFor_CSE, password),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Password,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"password"
		},
	{ ATF_POINTER, 3, offsetof(struct Ext_CallBarringInfoFor_CSE, wrongPasswordAttemptsCounter),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WrongPasswordAttemptsCounter,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"wrongPasswordAttemptsCounter"
		},
	{ ATF_POINTER, 2, offsetof(struct Ext_CallBarringInfoFor_CSE, notificationToCSE),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"notificationToCSE"
		},
	{ ATF_POINTER, 1, offsetof(struct Ext_CallBarringInfoFor_CSE, extensionContainer),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
};
static const ber_tlv_tag_t asn_DEF_Ext_CallBarringInfoFor_CSE_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Ext_CallBarringInfoFor_CSE_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ss-Code */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* callBarringFeatureList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* password */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* wrongPasswordAttemptsCounter */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* notificationToCSE */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* extensionContainer */
};
static asn_SEQUENCE_specifics_t asn_SPC_Ext_CallBarringInfoFor_CSE_specs_1 = {
	sizeof(struct Ext_CallBarringInfoFor_CSE),
	offsetof(struct Ext_CallBarringInfoFor_CSE, _asn_ctx),
	asn_MAP_Ext_CallBarringInfoFor_CSE_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Ext_CallBarringInfoFor_CSE = {
	"Ext-CallBarringInfoFor-CSE",
	"Ext-CallBarringInfoFor-CSE",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Ext_CallBarringInfoFor_CSE_tags_1,
	sizeof(asn_DEF_Ext_CallBarringInfoFor_CSE_tags_1)
		/sizeof(asn_DEF_Ext_CallBarringInfoFor_CSE_tags_1[0]), /* 1 */
	asn_DEF_Ext_CallBarringInfoFor_CSE_tags_1,	/* Same as above */
	sizeof(asn_DEF_Ext_CallBarringInfoFor_CSE_tags_1)
		/sizeof(asn_DEF_Ext_CallBarringInfoFor_CSE_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Ext_CallBarringInfoFor_CSE_1,
	6,	/* Elements count */
	&asn_SPC_Ext_CallBarringInfoFor_CSE_specs_1	/* Additional specs */
};

