/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#include "Ext-SS-Info.h"

static asn_TYPE_member_t asn_MBR_Ext_SS_Info_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Ext_SS_Info, choice.forwardingInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ext_ForwInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"forwardingInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Ext_SS_Info, choice.callBarringInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ext_CallBarInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callBarringInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Ext_SS_Info, choice.cug_Info),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CUG_Info,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cug-Info"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Ext_SS_Info, choice.ss_Data),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ext_SS_Data,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ss-Data"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Ext_SS_Info, choice.emlpp_Info),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EMLPP_Info,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"emlpp-Info"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Ext_SS_Info_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* forwardingInfo */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* callBarringInfo */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* cug-Info */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ss-Data */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* emlpp-Info */
};
static asn_CHOICE_specifics_t asn_SPC_Ext_SS_Info_specs_1 = {
	sizeof(struct Ext_SS_Info),
	offsetof(struct Ext_SS_Info, _asn_ctx),
	offsetof(struct Ext_SS_Info, present),
	sizeof(((struct Ext_SS_Info *)0)->present),
	asn_MAP_Ext_SS_Info_tag2el_1,
	5,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Ext_SS_Info = {
	"Ext-SS-Info",
	"Ext-SS-Info",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Ext_SS_Info_1,
	5,	/* Elements count */
	&asn_SPC_Ext_SS_Info_specs_1	/* Additional specs */
};

