/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-SS-DataTypes"
 * 	found in "MAP-SS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#include "ForwardingFeature.h"

static asn_TYPE_member_t asn_MBR_ForwardingFeature_1[] = {
	{ ATF_POINTER, 7, offsetof(struct ForwardingFeature, basicService),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_BasicServiceCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"basicService"
		},
	{ ATF_POINTER, 6, offsetof(struct ForwardingFeature, ss_Status),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SS_Status,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ss-Status"
		},
	{ ATF_POINTER, 5, offsetof(struct ForwardingFeature, forwardedToNumber),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ISDN_AddressString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"forwardedToNumber"
		},
	{ ATF_POINTER, 4, offsetof(struct ForwardingFeature, forwardedToSubaddress),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ISDN_SubaddressString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"forwardedToSubaddress"
		},
	{ ATF_POINTER, 3, offsetof(struct ForwardingFeature, forwardingOptions),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ForwardingOptions,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"forwardingOptions"
		},
	{ ATF_POINTER, 2, offsetof(struct ForwardingFeature, noReplyConditionTime),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NoReplyConditionTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"noReplyConditionTime"
		},
	{ ATF_POINTER, 1, offsetof(struct ForwardingFeature, longForwardedToNumber),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FTN_AddressString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"longForwardedToNumber"
		},
};
static const ber_tlv_tag_t asn_DEF_ForwardingFeature_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ForwardingFeature_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* bearerService */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 }, /* teleservice */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 }, /* ss-Status */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* forwardedToNumber */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 4, 0, 0 }, /* forwardingOptions */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 5, 0, 0 }, /* noReplyConditionTime */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 3, 0, 0 }, /* forwardedToSubaddress */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 6, 0, 0 } /* longForwardedToNumber */
};
static asn_SEQUENCE_specifics_t asn_SPC_ForwardingFeature_specs_1 = {
	sizeof(struct ForwardingFeature),
	offsetof(struct ForwardingFeature, _asn_ctx),
	asn_MAP_ForwardingFeature_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	8	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ForwardingFeature = {
	"ForwardingFeature",
	"ForwardingFeature",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ForwardingFeature_tags_1,
	sizeof(asn_DEF_ForwardingFeature_tags_1)
		/sizeof(asn_DEF_ForwardingFeature_tags_1[0]), /* 1 */
	asn_DEF_ForwardingFeature_tags_1,	/* Same as above */
	sizeof(asn_DEF_ForwardingFeature_tags_1)
		/sizeof(asn_DEF_ForwardingFeature_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ForwardingFeature_1,
	7,	/* Elements count */
	&asn_SPC_ForwardingFeature_specs_1	/* Additional specs */
};

