/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#include "ForwardAccessSignalling-Arg.h"

static asn_TYPE_member_t asn_MBR_ForwardAccessSignalling_Arg_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ForwardAccessSignalling_Arg, an_APDU),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AccessNetworkSignalInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"an-APDU"
		},
	{ ATF_POINTER, 19, offsetof(struct ForwardAccessSignalling_Arg, integrityProtectionInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IntegrityProtectionInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"integrityProtectionInfo"
		},
	{ ATF_POINTER, 18, offsetof(struct ForwardAccessSignalling_Arg, encryptionInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EncryptionInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"encryptionInfo"
		},
	{ ATF_POINTER, 17, offsetof(struct ForwardAccessSignalling_Arg, keyStatus),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_KeyStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"keyStatus"
		},
	{ ATF_POINTER, 16, offsetof(struct ForwardAccessSignalling_Arg, allowedGSM_Algorithms),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AllowedGSM_Algorithms,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"allowedGSM-Algorithms"
		},
	{ ATF_POINTER, 15, offsetof(struct ForwardAccessSignalling_Arg, allowedUMTS_Algorithms),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AllowedUMTS_Algorithms,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"allowedUMTS-Algorithms"
		},
	{ ATF_POINTER, 14, offsetof(struct ForwardAccessSignalling_Arg, radioResourceInformation),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioResourceInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"radioResourceInformation"
		},
	{ ATF_POINTER, 13, offsetof(struct ForwardAccessSignalling_Arg, extensionContainer),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
	{ ATF_POINTER, 12, offsetof(struct ForwardAccessSignalling_Arg, radioResourceList),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioResourceList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"radioResourceList"
		},
	{ ATF_POINTER, 11, offsetof(struct ForwardAccessSignalling_Arg, bssmap_ServiceHandover),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BSSMAP_ServiceHandover,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bssmap-ServiceHandover"
		},
	{ ATF_POINTER, 10, offsetof(struct ForwardAccessSignalling_Arg, ranap_ServiceHandover),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANAP_ServiceHandover,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ranap-ServiceHandover"
		},
	{ ATF_POINTER, 9, offsetof(struct ForwardAccessSignalling_Arg, bssmap_ServiceHandoverList),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BSSMAP_ServiceHandoverList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bssmap-ServiceHandoverList"
		},
	{ ATF_POINTER, 8, offsetof(struct ForwardAccessSignalling_Arg, currentlyUsedCodec),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Codec,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"currentlyUsedCodec"
		},
	{ ATF_POINTER, 7, offsetof(struct ForwardAccessSignalling_Arg, iuSupportedCodecsList),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SupportedCodecsList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iuSupportedCodecsList"
		},
	{ ATF_POINTER, 6, offsetof(struct ForwardAccessSignalling_Arg, rab_ConfigurationIndicator),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rab-ConfigurationIndicator"
		},
	{ ATF_POINTER, 5, offsetof(struct ForwardAccessSignalling_Arg, iuSelectedCodec),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Codec,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iuSelectedCodec"
		},
	{ ATF_POINTER, 4, offsetof(struct ForwardAccessSignalling_Arg, alternativeChannelType),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioResourceInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alternativeChannelType"
		},
	{ ATF_POINTER, 3, offsetof(struct ForwardAccessSignalling_Arg, tracePropagationList),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TracePropagationList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tracePropagationList"
		},
	{ ATF_POINTER, 2, offsetof(struct ForwardAccessSignalling_Arg, aoipSupportedCodecsListAnchor),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AoIPCodecsList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aoipSupportedCodecsListAnchor"
		},
	{ ATF_POINTER, 1, offsetof(struct ForwardAccessSignalling_Arg, aoipSelectedCodecTarget),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AoIPCodec,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aoipSelectedCodecTarget"
		},
};
static const ber_tlv_tag_t asn_DEF_ForwardAccessSignalling_Arg_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ForwardAccessSignalling_Arg_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* an-APDU */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* integrityProtectionInfo */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* encryptionInfo */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 }, /* keyStatus */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 7, 0, 0 }, /* extensionContainer */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* allowedGSM-Algorithms */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* allowedUMTS-Algorithms */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* radioResourceInformation */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 8, 0, 0 }, /* radioResourceList */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 10, 0, 0 }, /* ranap-ServiceHandover */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* bssmap-ServiceHandover */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 11, 0, 0 }, /* bssmap-ServiceHandoverList */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 12, 0, 0 }, /* currentlyUsedCodec */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 13, 0, 0 }, /* iuSupportedCodecsList */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 14, 0, 0 }, /* rab-ConfigurationIndicator */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 15, 0, 0 }, /* iuSelectedCodec */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 16, 0, 0 }, /* alternativeChannelType */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* tracePropagationList */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* aoipSupportedCodecsListAnchor */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 } /* aoipSelectedCodecTarget */
};
static asn_SEQUENCE_specifics_t asn_SPC_ForwardAccessSignalling_Arg_specs_1 = {
	sizeof(struct ForwardAccessSignalling_Arg),
	offsetof(struct ForwardAccessSignalling_Arg, _asn_ctx),
	asn_MAP_ForwardAccessSignalling_Arg_tag2el_1,
	20,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	7,	/* Start extensions */
	21	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ForwardAccessSignalling_Arg = {
	"ForwardAccessSignalling-Arg",
	"ForwardAccessSignalling-Arg",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ForwardAccessSignalling_Arg_tags_1,
	sizeof(asn_DEF_ForwardAccessSignalling_Arg_tags_1)
		/sizeof(asn_DEF_ForwardAccessSignalling_Arg_tags_1[0]) - 1, /* 1 */
	asn_DEF_ForwardAccessSignalling_Arg_tags_1,	/* Same as above */
	sizeof(asn_DEF_ForwardAccessSignalling_Arg_tags_1)
		/sizeof(asn_DEF_ForwardAccessSignalling_Arg_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_ForwardAccessSignalling_Arg_1,
	20,	/* Elements count */
	&asn_SPC_ForwardAccessSignalling_Arg_specs_1	/* Additional specs */
};

