/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_GSMMAPLocalErrorcode_H_
#define	_GSMMAPLocalErrorcode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GSMMAPLocalErrorcode {
	GSMMAPLocalErrorcode_systemFailure	= 34,
	GSMMAPLocalErrorcode_dataMissing	= 35,
	GSMMAPLocalErrorcode_unexpectedDataValue	= 36,
	GSMMAPLocalErrorcode_facilityNotSupported	= 21,
	GSMMAPLocalErrorcode_incompatibleTerminal	= 28,
	GSMMAPLocalErrorcode_resourceLimitation	= 51,
	GSMMAPLocalErrorcode_unknownSubscriber	= 1,
	GSMMAPLocalErrorcode_numberChanged	= 44,
	GSMMAPLocalErrorcode_unknownMSC	= 3,
	GSMMAPLocalErrorcode_unidentifiedSubscriber	= 5,
	GSMMAPLocalErrorcode_unknownEquipment	= 7,
	GSMMAPLocalErrorcode_roamingNotAllowed	= 8,
	GSMMAPLocalErrorcode_illegalSubscriber	= 9,
	GSMMAPLocalErrorcode_illegalEquipment	= 12,
	GSMMAPLocalErrorcode_bearerServiceNotProvisioned	= 10,
	GSMMAPLocalErrorcode_teleserviceNotProvisioned	= 11,
	GSMMAPLocalErrorcode_noHandoverNumberAvailable	= 25,
	GSMMAPLocalErrorcode_subsequentHandoverFailure	= 26,
	GSMMAPLocalErrorcode_targetCellOutsideGroupCallArea	= 42,
	GSMMAPLocalErrorcode_tracingBufferFull	= 40,
	GSMMAPLocalErrorcode_noRoamingNumberAvailable	= 39,
	GSMMAPLocalErrorcode_absentSubscriber	= 27,
	GSMMAPLocalErrorcode_busySubscriber	= 45,
	GSMMAPLocalErrorcode_noSubscriberReply	= 46,
	GSMMAPLocalErrorcode_callBarred	= 13,
	GSMMAPLocalErrorcode_forwardingViolation	= 14,
	GSMMAPLocalErrorcode_forwardingFailed	= 47,
	GSMMAPLocalErrorcode_cug_Reject	= 15,
	GSMMAPLocalErrorcode_or_NotAllowed	= 48,
	GSMMAPLocalErrorcode_ati_NotAllowed	= 49,
	GSMMAPLocalErrorcode_atsi_NotAllowed	= 60,
	GSMMAPLocalErrorcode_atm_NotAllowed	= 61,
	GSMMAPLocalErrorcode_informationNotAvailabl	= 62,
	GSMMAPLocalErrorcode_illegalSS_Operation	= 16,
	GSMMAPLocalErrorcode_ss_ErrorStatus	= 17,
	GSMMAPLocalErrorcode_ss_NotAvailable	= 18,
	GSMMAPLocalErrorcode_ss_SubscriptionViolatio	= 19,
	GSMMAPLocalErrorcode_ss_Incompatibility	= 20,
	GSMMAPLocalErrorcode_unknownAlphabe	= 71,
	GSMMAPLocalErrorcode_ussd_Busy	= 72,
	GSMMAPLocalErrorcode_pw_RegistrationFailur	= 37,
	GSMMAPLocalErrorcode_negativePW_Check	= 38,
	GSMMAPLocalErrorcode_numberOfPW_AttemptsViolation	= 43,
	GSMMAPLocalErrorcode_shortTermDenial	= 29,
	GSMMAPLocalErrorcode_longTermDenial	= 30,
	GSMMAPLocalErrorcode_subscriberBusyForMT_SMS	= 31,
	GSMMAPLocalErrorcode_sm_DeliveryFailure	= 32,
	GSMMAPLocalErrorcode_messageWaitingListFull	= 33,
	GSMMAPLocalErrorcode_absentSubscriberSM	= 6,
	GSMMAPLocalErrorcode_noGroupCallNumberAvailable	= 50,
	GSMMAPLocalErrorcode_unauthorizedRequestingNetwork	= 52,
	GSMMAPLocalErrorcode_unauthorizedLCSClient	= 53,
	GSMMAPLocalErrorcode_positionMethodFailure	= 54,
	GSMMAPLocalErrorcode_unknownOrUnreachableLCSClient	= 58,
	GSMMAPLocalErrorcode_mm_EventNotSupported	= 59,
	GSMMAPLocalErrorcode_secureTransportError	= 4
} e_GSMMAPLocalErrorcode;

/* GSMMAPLocalErrorcode */
typedef long	 GSMMAPLocalErrorcode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GSMMAPLocalErrorcode;
asn_struct_free_f GSMMAPLocalErrorcode_free;
asn_struct_print_f GSMMAPLocalErrorcode_print;
asn_constr_check_f GSMMAPLocalErrorcode_constraint;
ber_type_decoder_f GSMMAPLocalErrorcode_decode_ber;
der_type_encoder_f GSMMAPLocalErrorcode_encode_der;
xer_type_decoder_f GSMMAPLocalErrorcode_decode_xer;
xer_type_encoder_f GSMMAPLocalErrorcode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _GSMMAPLocalErrorcode_H_ */
#include <asn_internal.h>
