/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_InvokeParameter_H_
#define	_InvokeParameter_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ANY.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InvokeParameter */
typedef ANY_t	 InvokeParameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InvokeParameter;
asn_struct_free_f InvokeParameter_free;
asn_struct_print_f InvokeParameter_print;
asn_constr_check_f InvokeParameter_constraint;
ber_type_decoder_f InvokeParameter_decode_ber;
der_type_encoder_f InvokeParameter_encode_der;
xer_type_decoder_f InvokeParameter_decode_xer;
xer_type_encoder_f InvokeParameter_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _InvokeParameter_H_ */
#include <asn_internal.h>
