/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_Invoke_H_
#define	_Invoke_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InvokeIdType.h"
#include "MAP-OPERATION.h"
#include "InvokeParameter.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Invoke */
typedef struct Invoke {
	InvokeIdType_t	 invokeID;
	InvokeIdType_t	*linkedID	/* OPTIONAL */;
	MAP_OPERATION_t	 opCode;
	InvokeParameter_t	*invokeparameter	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Invoke_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Invoke;

#ifdef __cplusplus
}
#endif

#endif	/* _Invoke_H_ */
#include <asn_internal.h>
