/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_KeyStatus_H_
#define	_KeyStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum KeyStatus {
	KeyStatus_old	= 0,
	KeyStatus_new	= 1
	/*
	 * Enumeration is extensible
	 */
} e_KeyStatus;

/* KeyStatus */
typedef long	 KeyStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KeyStatus;
asn_struct_free_f KeyStatus_free;
asn_struct_print_f KeyStatus_print;
asn_constr_check_f KeyStatus_constraint;
ber_type_decoder_f KeyStatus_decode_ber;
der_type_encoder_f KeyStatus_encode_der;
xer_type_decoder_f KeyStatus_decode_xer;
xer_type_encoder_f KeyStatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _KeyStatus_H_ */
#include <asn_internal.h>
