/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_LocalErrorcode_H_
#define	_LocalErrorcode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GSMMAPLocalErrorcode.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LocalErrorcode */
typedef GSMMAPLocalErrorcode_t	 LocalErrorcode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LocalErrorcode;
asn_struct_free_f LocalErrorcode_free;
asn_struct_print_f LocalErrorcode_print;
asn_constr_check_f LocalErrorcode_constraint;
ber_type_decoder_f LocalErrorcode_decode_ber;
der_type_encoder_f LocalErrorcode_encode_der;
xer_type_decoder_f LocalErrorcode_decode_xer;
xer_type_encoder_f LocalErrorcode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LocalErrorcode_H_ */
#include <asn_internal.h>
