/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-DialogueInformation"
 * 	found in "MAP-DialogueInformation.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_MAP_ProviderAbortReason_H_
#define	_MAP_ProviderAbortReason_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MAP_ProviderAbortReason {
	MAP_ProviderAbortReason_abnormalDialogue	= 0,
	MAP_ProviderAbortReason_invalidPDU	= 1
} e_MAP_ProviderAbortReason;

/* MAP-ProviderAbortReason */
typedef long	 MAP_ProviderAbortReason_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MAP_ProviderAbortReason;
asn_struct_free_f MAP_ProviderAbortReason_free;
asn_struct_print_f MAP_ProviderAbortReason_print;
asn_constr_check_f MAP_ProviderAbortReason_constraint;
ber_type_decoder_f MAP_ProviderAbortReason_decode_ber;
der_type_encoder_f MAP_ProviderAbortReason_encode_der;
xer_type_decoder_f MAP_ProviderAbortReason_decode_xer;
xer_type_encoder_f MAP_ProviderAbortReason_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MAP_ProviderAbortReason_H_ */
#include <asn_internal.h>
