/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_MAP_ERROR_H_
#define	_MAP_ERROR_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LocalErrorcode.h"
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MAP_ERROR_PR {
	MAP_ERROR_PR_NOTHING,	/* No components present */
	MAP_ERROR_PR_localValue,
	MAP_ERROR_PR_globalValue
} MAP_ERROR_PR;

/* MAP-ERROR */
typedef struct MAP_ERROR {
	MAP_ERROR_PR present;
	union MAP_ERROR_u {
		LocalErrorcode_t	 localValue;
		OBJECT_IDENTIFIER_t	 globalValue;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MAP_ERROR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MAP_ERROR;

#ifdef __cplusplus
}
#endif

#endif	/* _MAP_ERROR_H_ */
#include <asn_internal.h>
