/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-DialogueInformation"
 * 	found in "MAP-DialogueInformation.asn"
 * 	`asn1c -pdu=auto`
 */

#include "MAP-DialoguePDU.h"

static asn_TYPE_member_t asn_MBR_MAP_DialoguePDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MAP_DialoguePDU, choice.map_open),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MAP_OpenInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"map-open"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAP_DialoguePDU, choice.map_accept),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MAP_AcceptInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"map-accept"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAP_DialoguePDU, choice.map_close),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MAP_CloseInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"map-close"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAP_DialoguePDU, choice.map_refuse),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MAP_RefuseInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"map-refuse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAP_DialoguePDU, choice.map_userAbort),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MAP_UserAbortInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"map-userAbort"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAP_DialoguePDU, choice.map_providerAbort),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MAP_ProviderAbortInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"map-providerAbort"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_MAP_DialoguePDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* map-open */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* map-accept */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* map-close */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* map-refuse */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* map-userAbort */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* map-providerAbort */
};
static asn_CHOICE_specifics_t asn_SPC_MAP_DialoguePDU_specs_1 = {
	sizeof(struct MAP_DialoguePDU),
	offsetof(struct MAP_DialoguePDU, _asn_ctx),
	offsetof(struct MAP_DialoguePDU, present),
	sizeof(((struct MAP_DialoguePDU *)0)->present),
	asn_MAP_MAP_DialoguePDU_tag2el_1,
	6,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_MAP_DialoguePDU = {
	"MAP-DialoguePDU",
	"MAP-DialoguePDU",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_MAP_DialoguePDU_1,
	6,	/* Elements count */
	&asn_SPC_MAP_DialoguePDU_specs_1	/* Additional specs */
};

