/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_NoteSubscriberDataModifiedArg_H_
#define	_NoteSubscriberDataModifiedArg_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IMSI.h"
#include "ISDN-AddressString.h"
#include <NULL.h>
#include "ServingNode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ext_ForwardingInfoFor_CSE;
struct Ext_CallBarringInfoFor_CSE;
struct ODB_Info;
struct CAMEL_SubscriptionInfo;
struct ExtensionContainer;
struct CSG_SubscriptionDataList;

/* NoteSubscriberDataModifiedArg */
typedef struct NoteSubscriberDataModifiedArg {
	IMSI_t	 imsi;
	ISDN_AddressString_t	 msisdn;
	struct Ext_ForwardingInfoFor_CSE	*forwardingInfoFor_CSE	/* OPTIONAL */;
	struct Ext_CallBarringInfoFor_CSE	*callBarringInfoFor_CSE	/* OPTIONAL */;
	struct ODB_Info	*odb_Info	/* OPTIONAL */;
	struct CAMEL_SubscriptionInfo	*camel_SubscriptionInfo	/* OPTIONAL */;
	NULL_t	*allInformationSent	/* OPTIONAL */;
	struct ExtensionContainer	*extensionContainer	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	ServingNode_t	*ue_reachable	/* OPTIONAL */;
	struct CSG_SubscriptionDataList	*csg_SubscriptionDataList	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NoteSubscriberDataModifiedArg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NoteSubscriberDataModifiedArg;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Ext-ForwardingInfoFor-CSE.h"
#include "Ext-CallBarringInfoFor-CSE.h"
#include "ODB-Info.h"
#include "CAMEL-SubscriptionInfo.h"
#include "ExtensionContainer.h"
#include "CSG-SubscriptionDataList.h"

#endif	/* _NoteSubscriberDataModifiedArg_H_ */
#include <asn_internal.h>
