/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_OperationLocalvalue_H_
#define	_OperationLocalvalue_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GSMMAPOperationLocalvalue.h"

#ifdef __cplusplus
extern "C" {
#endif

/* OperationLocalvalue */
typedef GSMMAPOperationLocalvalue_t	 OperationLocalvalue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OperationLocalvalue;
asn_struct_free_f OperationLocalvalue_free;
asn_struct_print_f OperationLocalvalue_print;
asn_constr_check_f OperationLocalvalue_constraint;
ber_type_decoder_f OperationLocalvalue_decode_ber;
der_type_encoder_f OperationLocalvalue_encode_der;
xer_type_decoder_f OperationLocalvalue_decode_xer;
xer_type_encoder_f OperationLocalvalue_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OperationLocalvalue_H_ */
#include <asn_internal.h>
