/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#include "OriginalComponentIdentifier.h"

static asn_TYPE_member_t asn_MBR_OriginalComponentIdentifier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OriginalComponentIdentifier, choice.operationCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OperationCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"operationCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OriginalComponentIdentifier, choice.errorCode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ErrorCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"errorCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OriginalComponentIdentifier, choice.userInfo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"userInfo"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_OriginalComponentIdentifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* operationCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* errorCode */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* userInfo */
};
static asn_CHOICE_specifics_t asn_SPC_OriginalComponentIdentifier_specs_1 = {
	sizeof(struct OriginalComponentIdentifier),
	offsetof(struct OriginalComponentIdentifier, _asn_ctx),
	offsetof(struct OriginalComponentIdentifier, present),
	sizeof(((struct OriginalComponentIdentifier *)0)->present),
	asn_MAP_OriginalComponentIdentifier_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_OriginalComponentIdentifier = {
	"OriginalComponentIdentifier",
	"OriginalComponentIdentifier",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_OriginalComponentIdentifier_1,
	3,	/* Elements count */
	&asn_SPC_OriginalComponentIdentifier_specs_1	/* Additional specs */
};

