/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-SS-DataTypes"
 * 	found in "MAP-SS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_OverrideCategory_H_
#define	_OverrideCategory_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OverrideCategory {
	OverrideCategory_overrideEnabled	= 0,
	OverrideCategory_overrideDisabled	= 1
} e_OverrideCategory;

/* OverrideCategory */
typedef long	 OverrideCategory_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OverrideCategory;
asn_struct_free_f OverrideCategory_free;
asn_struct_print_f OverrideCategory_print;
asn_constr_check_f OverrideCategory_constraint;
ber_type_decoder_f OverrideCategory_decode_ber;
der_type_encoder_f OverrideCategory_encode_der;
xer_type_decoder_f OverrideCategory_decode_xer;
xer_type_encoder_f OverrideCategory_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OverrideCategory_H_ */
#include <asn_internal.h>
