/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#include "PlmnContainer.h"

static int
memb_OCTET_STRING_constraint_5(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_operatorSS_Code_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 16)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_operatorSS_Code_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		memb_OCTET_STRING_constraint_5,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_operatorSS_Code_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_operatorSS_Code_specs_5 = {
	sizeof(struct operatorSS_Code),
	offsetof(struct operatorSS_Code, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_operatorSS_Code_5 = {
	"operatorSS-Code",
	"operatorSS-Code",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_operatorSS_Code_tags_5,
	sizeof(asn_DEF_operatorSS_Code_tags_5)
		/sizeof(asn_DEF_operatorSS_Code_tags_5[0]) - 1, /* 1 */
	asn_DEF_operatorSS_Code_tags_5,	/* Same as above */
	sizeof(asn_DEF_operatorSS_Code_tags_5)
		/sizeof(asn_DEF_operatorSS_Code_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_operatorSS_Code_5,
	1,	/* Single element */
	&asn_SPC_operatorSS_Code_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_PlmnContainer_1[] = {
	{ ATF_POINTER, 4, offsetof(struct PlmnContainer, msisdn),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ISDN_AddressString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msisdn"
		},
	{ ATF_POINTER, 3, offsetof(struct PlmnContainer, category),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Category,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"category"
		},
	{ ATF_POINTER, 2, offsetof(struct PlmnContainer, basicService),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_BasicServiceCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"basicService"
		},
	{ ATF_POINTER, 1, offsetof(struct PlmnContainer, operatorSS_Code),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_operatorSS_Code_5,
		memb_operatorSS_Code_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"operatorSS-Code"
		},
};
static const ber_tlv_tag_t asn_DEF_PlmnContainer_tags_1[] = {
	(ASN_TAG_CLASS_PRIVATE | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PlmnContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* msisdn */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* category */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* bearerService */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* teleservice */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 } /* operatorSS-Code */
};
static asn_SEQUENCE_specifics_t asn_SPC_PlmnContainer_specs_1 = {
	sizeof(struct PlmnContainer),
	offsetof(struct PlmnContainer, _asn_ctx),
	asn_MAP_PlmnContainer_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PlmnContainer = {
	"PlmnContainer",
	"PlmnContainer",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PlmnContainer_tags_1,
	sizeof(asn_DEF_PlmnContainer_tags_1)
		/sizeof(asn_DEF_PlmnContainer_tags_1[0]) - 1, /* 1 */
	asn_DEF_PlmnContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_PlmnContainer_tags_1)
		/sizeof(asn_DEF_PlmnContainer_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_PlmnContainer_1,
	4,	/* Elements count */
	&asn_SPC_PlmnContainer_specs_1	/* Additional specs */
};

