/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#include "PrepareHO-ArgOld.h"

static asn_TYPE_member_t asn_MBR_PrepareHO_ArgOld_1[] = {
	{ ATF_POINTER, 3, offsetof(struct PrepareHO_ArgOld, targetCellId),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_GlobalCellId,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"targetCellId"
		},
	{ ATF_POINTER, 2, offsetof(struct PrepareHO_ArgOld, ho_NumberNotRequired),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ho-NumberNotRequired"
		},
	{ ATF_POINTER, 1, offsetof(struct PrepareHO_ArgOld, bss_APDU),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Bss_APDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bss-APDU"
		},
};
static const ber_tlv_tag_t asn_DEF_PrepareHO_ArgOld_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PrepareHO_ArgOld_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* targetCellId */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 1, 0, 0 }, /* ho-NumberNotRequired */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 } /* bss-APDU */
};
static asn_SEQUENCE_specifics_t asn_SPC_PrepareHO_ArgOld_specs_1 = {
	sizeof(struct PrepareHO_ArgOld),
	offsetof(struct PrepareHO_ArgOld, _asn_ctx),
	asn_MAP_PrepareHO_ArgOld_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PrepareHO_ArgOld = {
	"PrepareHO-ArgOld",
	"PrepareHO-ArgOld",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PrepareHO_ArgOld_tags_1,
	sizeof(asn_DEF_PrepareHO_ArgOld_tags_1)
		/sizeof(asn_DEF_PrepareHO_ArgOld_tags_1[0]), /* 1 */
	asn_DEF_PrepareHO_ArgOld_tags_1,	/* Same as above */
	sizeof(asn_DEF_PrepareHO_ArgOld_tags_1)
		/sizeof(asn_DEF_PrepareHO_ArgOld_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PrepareHO_ArgOld_1,
	3,	/* Elements count */
	&asn_SPC_PrepareHO_ArgOld_specs_1	/* Additional specs */
};

