/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-DialogueInformation"
 * 	found in "MAP-DialogueInformation.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_ProcedureCancellationReason_H_
#define	_ProcedureCancellationReason_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProcedureCancellationReason {
	ProcedureCancellationReason_handoverCancellation	= 0,
	ProcedureCancellationReason_radioChannelRelease	= 1,
	ProcedureCancellationReason_networkPathRelease	= 2,
	ProcedureCancellationReason_callRelease	= 3,
	ProcedureCancellationReason_associatedProcedureFailure	= 4,
	ProcedureCancellationReason_tandemDialogueRelease	= 5,
	ProcedureCancellationReason_remoteOperationsFailure	= 6
} e_ProcedureCancellationReason;

/* ProcedureCancellationReason */
typedef long	 ProcedureCancellationReason_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProcedureCancellationReason;
asn_struct_free_f ProcedureCancellationReason_free;
asn_struct_print_f ProcedureCancellationReason_print;
asn_constr_check_f ProcedureCancellationReason_constraint;
ber_type_decoder_f ProcedureCancellationReason_decode_ber;
der_type_encoder_f ProcedureCancellationReason_encode_der;
xer_type_decoder_f ProcedureCancellationReason_decode_xer;
xer_type_encoder_f ProcedureCancellationReason_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ProcedureCancellationReason_H_ */
#include <asn_internal.h>
