/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_ProtectedPayload_H_
#define	_ProtectedPayload_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProtectedPayload */
typedef OCTET_STRING_t	 ProtectedPayload_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtectedPayload;
asn_struct_free_f ProtectedPayload_free;
asn_struct_print_f ProtectedPayload_print;
asn_constr_check_f ProtectedPayload_constraint;
ber_type_decoder_f ProtectedPayload_decode_ber;
der_type_encoder_f ProtectedPayload_encode_der;
xer_type_decoder_f ProtectedPayload_decode_xer;
xer_type_encoder_f ProtectedPayload_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtectedPayload_H_ */
#include <asn_internal.h>
