/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_PurgeMSArgV2_H_
#define	_PurgeMSArgV2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IMSI.h"
#include "ISDN-AddressString.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PurgeMSArgV2 */
typedef struct PurgeMSArgV2 {
	IMSI_t	 imsi;
	ISDN_AddressString_t	*vlr_Number	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PurgeMSArgV2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PurgeMSArgV2;

#ifdef __cplusplus
}
#endif

#endif	/* _PurgeMSArgV2_H_ */
#include <asn_internal.h>
