/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-CH-DataTypes"
 * 	found in "MAP-CH-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_ReportingState_H_
#define	_ReportingState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReportingState {
	ReportingState_stopMonitoring	= 0,
	ReportingState_startMonitoring	= 1
	/*
	 * Enumeration is extensible
	 */
} e_ReportingState;

/* ReportingState */
typedef long	 ReportingState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportingState;
asn_struct_free_f ReportingState_free;
asn_struct_print_f ReportingState_print;
asn_constr_check_f ReportingState_constraint;
ber_type_decoder_f ReportingState_decode_ber;
der_type_encoder_f ReportingState_encode_der;
xer_type_decoder_f ReportingState_decode_xer;
xer_type_encoder_f ReportingState_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ReportingState_H_ */
#include <asn_internal.h>
