/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#include "RequestedSubscriptionInfo.h"

static asn_TYPE_member_t asn_MBR_RequestedSubscriptionInfo_1[] = {
	{ ATF_POINTER, 9, offsetof(struct RequestedSubscriptionInfo, requestedSS_Info),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SS_ForBS_Code,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestedSS-Info"
		},
	{ ATF_POINTER, 8, offsetof(struct RequestedSubscriptionInfo, odb),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"odb"
		},
	{ ATF_POINTER, 7, offsetof(struct RequestedSubscriptionInfo, requestedCAMEL_SubscriptionInfo),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RequestedCAMEL_SubscriptionInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestedCAMEL-SubscriptionInfo"
		},
	{ ATF_POINTER, 6, offsetof(struct RequestedSubscriptionInfo, supportedVLR_CAMEL_Phases),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"supportedVLR-CAMEL-Phases"
		},
	{ ATF_POINTER, 5, offsetof(struct RequestedSubscriptionInfo, supportedSGSN_CAMEL_Phases),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"supportedSGSN-CAMEL-Phases"
		},
	{ ATF_POINTER, 4, offsetof(struct RequestedSubscriptionInfo, extensionContainer),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
	{ ATF_POINTER, 3, offsetof(struct RequestedSubscriptionInfo, additionalRequestedCAMEL_SubscriptionInfo),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AdditionalRequestedCAMEL_SubscriptionInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"additionalRequestedCAMEL-SubscriptionInfo"
		},
	{ ATF_POINTER, 2, offsetof(struct RequestedSubscriptionInfo, msisdn_BS_List),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msisdn-BS-List"
		},
	{ ATF_POINTER, 1, offsetof(struct RequestedSubscriptionInfo, csg_SubscriptionDataRequested),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"csg-SubscriptionDataRequested"
		},
};
static const ber_tlv_tag_t asn_DEF_RequestedSubscriptionInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RequestedSubscriptionInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* requestedSS-Info */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* odb */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* requestedCAMEL-SubscriptionInfo */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* supportedVLR-CAMEL-Phases */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* supportedSGSN-CAMEL-Phases */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* extensionContainer */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* additionalRequestedCAMEL-SubscriptionInfo */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 7, 0, 0 }, /* msisdn-BS-List */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 8, 0, 0 } /* csg-SubscriptionDataRequested */
};
static asn_SEQUENCE_specifics_t asn_SPC_RequestedSubscriptionInfo_specs_1 = {
	sizeof(struct RequestedSubscriptionInfo),
	offsetof(struct RequestedSubscriptionInfo, _asn_ctx),
	asn_MAP_RequestedSubscriptionInfo_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	10	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RequestedSubscriptionInfo = {
	"RequestedSubscriptionInfo",
	"RequestedSubscriptionInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RequestedSubscriptionInfo_tags_1,
	sizeof(asn_DEF_RequestedSubscriptionInfo_tags_1)
		/sizeof(asn_DEF_RequestedSubscriptionInfo_tags_1[0]), /* 1 */
	asn_DEF_RequestedSubscriptionInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_RequestedSubscriptionInfo_tags_1)
		/sizeof(asn_DEF_RequestedSubscriptionInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RequestedSubscriptionInfo_1,
	9,	/* Elements count */
	&asn_SPC_RequestedSubscriptionInfo_specs_1	/* Additional specs */
};

