/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-CH-DataTypes"
 * 	found in "MAP-CH-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_ResumeCallHandlingArg_H_
#define	_ResumeCallHandlingArg_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CallReferenceNumber.h"
#include "IMSI.h"
#include <NULL.h>
#include "ISDN-AddressString.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ext_BasicServiceCode;
struct ForwardingData;
struct CUG_CheckInfo;
struct O_CSI;
struct ExtensionContainer;
struct UU_Data;
struct D_CSI;
struct O_BcsmCamelTDPCriteriaList;

/* ResumeCallHandlingArg */
typedef struct ResumeCallHandlingArg {
	CallReferenceNumber_t	*callReferenceNumber	/* OPTIONAL */;
	struct Ext_BasicServiceCode	*basicServiceGroup	/* OPTIONAL */;
	struct ForwardingData	*forwardingData	/* OPTIONAL */;
	IMSI_t	*imsi	/* OPTIONAL */;
	struct CUG_CheckInfo	*cug_CheckInfo	/* OPTIONAL */;
	struct O_CSI	*o_CSI	/* OPTIONAL */;
	struct ExtensionContainer	*extensionContainer	/* OPTIONAL */;
	NULL_t	*ccbs_Possible	/* OPTIONAL */;
	ISDN_AddressString_t	*msisdn	/* OPTIONAL */;
	struct UU_Data	*uu_Data	/* OPTIONAL */;
	NULL_t	*allInformationSent	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct D_CSI	*d_csi	/* OPTIONAL */;
	struct O_BcsmCamelTDPCriteriaList	*o_BcsmCamelTDPCriteriaList	/* OPTIONAL */;
	struct Ext_BasicServiceCode	*basicServiceGroup2	/* OPTIONAL */;
	NULL_t	*mtRoamingRetry	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResumeCallHandlingArg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResumeCallHandlingArg;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Ext-BasicServiceCode.h"
#include "ForwardingData.h"
#include "CUG-CheckInfo.h"
#include "O-CSI.h"
#include "ExtensionContainer.h"
#include "UU-Data.h"
#include "D-CSI.h"
#include "O-BcsmCamelTDPCriteriaList.h"

#endif	/* _ResumeCallHandlingArg_H_ */
#include <asn_internal.h>
