/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_ReturnError_H_
#define	_ReturnError_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InvokeIdType.h"
#include "MAP-ERROR.h"
#include "ReturnErrorParameter.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReturnError */
typedef struct ReturnError {
	InvokeIdType_t	 invokeID;
	MAP_ERROR_t	 errorCode;
	ReturnErrorParameter_t	*parameter	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReturnError_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReturnError;

#ifdef __cplusplus
}
#endif

#endif	/* _ReturnError_H_ */
#include <asn_internal.h>
