/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_SecureTransportArg_H_
#define	_SecureTransportArg_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SecurityHeader.h"
#include "ProtectedPayload.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SecureTransportArg */
typedef struct SecureTransportArg {
	SecurityHeader_t	 securityHeader;
	ProtectedPayload_t	*protectedPayload	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecureTransportArg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecureTransportArg;

#ifdef __cplusplus
}
#endif

#endif	/* _SecureTransportArg_H_ */
#include <asn_internal.h>
