/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#include "SendAuthenticationInfoArg.h"

static asn_TYPE_member_t asn_MBR_SendAuthenticationInfoArg_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SendAuthenticationInfoArg, imsi),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IMSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"imsi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SendAuthenticationInfoArg, numberOfRequestedVectors),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NumberOfRequestedVectors,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfRequestedVectors"
		},
	{ ATF_POINTER, 8, offsetof(struct SendAuthenticationInfoArg, segmentationProhibited),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"segmentationProhibited"
		},
	{ ATF_POINTER, 7, offsetof(struct SendAuthenticationInfoArg, immediateResponsePreferred),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"immediateResponsePreferred"
		},
	{ ATF_POINTER, 6, offsetof(struct SendAuthenticationInfoArg, re_synchronisationInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Re_synchronisationInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"re-synchronisationInfo"
		},
	{ ATF_POINTER, 5, offsetof(struct SendAuthenticationInfoArg, extensionContainer),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
	{ ATF_POINTER, 4, offsetof(struct SendAuthenticationInfoArg, requestingNodeType),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RequestingNodeType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestingNodeType"
		},
	{ ATF_POINTER, 3, offsetof(struct SendAuthenticationInfoArg, requestingPLMN_Id),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PLMN_Id,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requestingPLMN-Id"
		},
	{ ATF_POINTER, 2, offsetof(struct SendAuthenticationInfoArg, numberOfRequestedAdditional_Vectors),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NumberOfRequestedVectors,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfRequestedAdditional-Vectors"
		},
	{ ATF_POINTER, 1, offsetof(struct SendAuthenticationInfoArg, additionalVectorsAreForEPS),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"additionalVectorsAreForEPS"
		},
};
static const ber_tlv_tag_t asn_DEF_SendAuthenticationInfoArg_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SendAuthenticationInfoArg_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* numberOfRequestedVectors */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 2, 0, 0 }, /* segmentationProhibited */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, 0, 0 }, /* re-synchronisationInfo */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* imsi */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 3, 0, 0 }, /* immediateResponsePreferred */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 5, 0, 0 }, /* extensionContainer */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 6, 0, 0 }, /* requestingNodeType */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 7, 0, 0 }, /* requestingPLMN-Id */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 8, 0, 0 }, /* numberOfRequestedAdditional-Vectors */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 9, 0, 0 } /* additionalVectorsAreForEPS */
};
static asn_SEQUENCE_specifics_t asn_SPC_SendAuthenticationInfoArg_specs_1 = {
	sizeof(struct SendAuthenticationInfoArg),
	offsetof(struct SendAuthenticationInfoArg, _asn_ctx),
	asn_MAP_SendAuthenticationInfoArg_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	11	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SendAuthenticationInfoArg = {
	"SendAuthenticationInfoArg",
	"SendAuthenticationInfoArg",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SendAuthenticationInfoArg_tags_1,
	sizeof(asn_DEF_SendAuthenticationInfoArg_tags_1)
		/sizeof(asn_DEF_SendAuthenticationInfoArg_tags_1[0]), /* 1 */
	asn_DEF_SendAuthenticationInfoArg_tags_1,	/* Same as above */
	sizeof(asn_DEF_SendAuthenticationInfoArg_tags_1)
		/sizeof(asn_DEF_SendAuthenticationInfoArg_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SendAuthenticationInfoArg_1,
	10,	/* Elements count */
	&asn_SPC_SendAuthenticationInfoArg_specs_1	/* Additional specs */
};

