/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_SendRoutingInfoResV2_H_
#define	_SendRoutingInfoResV2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IMSI.h"
#include "RoutingInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CUG_CheckInfo;

/* SendRoutingInfoResV2 */
typedef struct SendRoutingInfoResV2 {
	IMSI_t	 imsi;
	RoutingInfo_t	 routingInfo;
	struct CUG_CheckInfo	*cug_CheckInfo	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SendRoutingInfoResV2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SendRoutingInfoResV2;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CUG-CheckInfo.h"

#endif	/* _SendRoutingInfoResV2_H_ */
#include <asn_internal.h>
