/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_SendIdentificationResV2_H_
#define	_SendIdentificationResV2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IMSI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TripletListold;

/* SendIdentificationResV2 */
typedef struct SendIdentificationResV2 {
	IMSI_t	*imsi	/* OPTIONAL */;
	struct TripletListold	*tripletList	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SendIdentificationResV2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SendIdentificationResV2;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TripletListold.h"

#endif	/* _SendIdentificationResV2_H_ */
#include <asn_internal.h>
