/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DummyMAP"
 * 	found in "GSMMAP.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_SendRoutingInfoArgV2_H_
#define	_SendRoutingInfoArgV2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ISDN-AddressString.h"
#include "NumberOfForwarding.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CUG_CheckInfo;
struct ExternalSignalInfo;

/* SendRoutingInfoArgV2 */
typedef struct SendRoutingInfoArgV2 {
	ISDN_AddressString_t	 msisdn;
	struct CUG_CheckInfo	*cug_CheckInfo	/* OPTIONAL */;
	NumberOfForwarding_t	*numberOfForwarding	/* OPTIONAL */;
	struct ExternalSignalInfo	*networkSignalInfo	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SendRoutingInfoArgV2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SendRoutingInfoArgV2;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CUG-CheckInfo.h"
#include "ExternalSignalInfo.h"

#endif	/* _SendRoutingInfoArgV2_H_ */
#include <asn_internal.h>
