/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-SS-DataTypes"
 * 	found in "MAP-SS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_ServiceIndicator_H_
#define	_ServiceIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServiceIndicator {
	ServiceIndicator_clir_invoked	= 0,
	ServiceIndicator_camel_invoked	= 1
} e_ServiceIndicator;

/* ServiceIndicator */
typedef BIT_STRING_t	 ServiceIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceIndicator;
asn_struct_free_f ServiceIndicator_free;
asn_struct_print_f ServiceIndicator_print;
asn_constr_check_f ServiceIndicator_constraint;
ber_type_decoder_f ServiceIndicator_decode_ber;
der_type_encoder_f ServiceIndicator_encode_der;
xer_type_decoder_f ServiceIndicator_decode_xer;
xer_type_encoder_f ServiceIndicator_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceIndicator_H_ */
#include <asn_internal.h>
