/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_ServingNode_H_
#define	_ServingNode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServingNode {
	ServingNode_mme	= 0
} e_ServingNode;

/* ServingNode */
typedef BIT_STRING_t	 ServingNode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServingNode;
asn_struct_free_f ServingNode_free;
asn_struct_print_f ServingNode_print;
asn_constr_check_f ServingNode_constraint;
ber_type_decoder_f ServingNode_decode_ber;
der_type_encoder_f ServingNode_encode_der;
xer_type_decoder_f ServingNode_decode_xer;
xer_type_encoder_f ServingNode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ServingNode_H_ */
#include <asn_internal.h>
