/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-CH-DataTypes"
 * 	found in "MAP-CH-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#ifndef	_SetReportingStateArg_H_
#define	_SetReportingStateArg_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IMSI.h"
#include "LMSI.h"
#include "ReportingState.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExtensionContainer;

/* SetReportingStateArg */
typedef struct SetReportingStateArg {
	IMSI_t	*imsi	/* OPTIONAL */;
	LMSI_t	*lmsi	/* OPTIONAL */;
	ReportingState_t	*ccbs_Monitoring	/* OPTIONAL */;
	struct ExtensionContainer	*extensionContainer	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetReportingStateArg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetReportingStateArg;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExtensionContainer.h"

#endif	/* _SetReportingStateArg_H_ */
#include <asn_internal.h>
