/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#include "SGSN-Capability.h"

static asn_TYPE_member_t asn_MBR_SGSN_Capability_1[] = {
	{ ATF_POINTER, 12, offsetof(struct SGSN_Capability, solsaSupportIndicator),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"solsaSupportIndicator"
		},
	{ ATF_POINTER, 11, offsetof(struct SGSN_Capability, extensionContainer),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
	{ ATF_POINTER, 10, offsetof(struct SGSN_Capability, superChargerSupportedInServingNetworkEntity),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SuperChargerInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"superChargerSupportedInServingNetworkEntity"
		},
	{ ATF_POINTER, 9, offsetof(struct SGSN_Capability, gprsEnhancementsSupportIndicator),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gprsEnhancementsSupportIndicator"
		},
	{ ATF_POINTER, 8, offsetof(struct SGSN_Capability, supportedCamelPhases),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SupportedCamelPhases,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"supportedCamelPhases"
		},
	{ ATF_POINTER, 7, offsetof(struct SGSN_Capability, supportedLCS_CapabilitySets),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SupportedLCS_CapabilitySets,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"supportedLCS-CapabilitySets"
		},
	{ ATF_POINTER, 6, offsetof(struct SGSN_Capability, offeredCamel4CSIs),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OfferedCamel4CSIs,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"offeredCamel4CSIs"
		},
	{ ATF_POINTER, 5, offsetof(struct SGSN_Capability, smsCallBarringSupportIndicator),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"smsCallBarringSupportIndicator"
		},
	{ ATF_POINTER, 4, offsetof(struct SGSN_Capability, supportedRAT_TypesIndicator),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SupportedRAT_Types,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"supportedRAT-TypesIndicator"
		},
	{ ATF_POINTER, 3, offsetof(struct SGSN_Capability, supportedFeatures),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SupportedFeatures,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"supportedFeatures"
		},
	{ ATF_POINTER, 2, offsetof(struct SGSN_Capability, t_adsDataRetrieval),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"t-adsDataRetrieval"
		},
	{ ATF_POINTER, 1, offsetof(struct SGSN_Capability, homogeneousSupportOfIMSVoiceOverPSSessions),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"homogeneousSupportOfIMSVoiceOverPSSessions"
		},
};
static const ber_tlv_tag_t asn_DEF_SGSN_Capability_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SGSN_Capability_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 0, 0, 0 }, /* solsaSupportIndicator */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* extensionContainer */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* superChargerSupportedInServingNetworkEntity */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* gprsEnhancementsSupportIndicator */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* supportedCamelPhases */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* supportedLCS-CapabilitySets */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* offeredCamel4CSIs */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* smsCallBarringSupportIndicator */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* supportedRAT-TypesIndicator */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* supportedFeatures */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* t-adsDataRetrieval */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 } /* homogeneousSupportOfIMSVoiceOverPSSessions */
};
static asn_SEQUENCE_specifics_t asn_SPC_SGSN_Capability_specs_1 = {
	sizeof(struct SGSN_Capability),
	offsetof(struct SGSN_Capability, _asn_ctx),
	asn_MAP_SGSN_Capability_tag2el_1,
	12,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* Start extensions */
	13	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SGSN_Capability = {
	"SGSN-Capability",
	"SGSN-Capability",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SGSN_Capability_tags_1,
	sizeof(asn_DEF_SGSN_Capability_tags_1)
		/sizeof(asn_DEF_SGSN_Capability_tags_1[0]), /* 1 */
	asn_DEF_SGSN_Capability_tags_1,	/* Same as above */
	sizeof(asn_DEF_SGSN_Capability_tags_1)
		/sizeof(asn_DEF_SGSN_Capability_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SGSN_Capability_1,
	12,	/* Elements count */
	&asn_SPC_SGSN_Capability_specs_1	/* Additional specs */
};

