/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#include "SS-CamelData.h"

static asn_TYPE_member_t asn_MBR_SS_CamelData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SS_CamelData, ss_EventList),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SS_EventList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ss-EventList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SS_CamelData, gsmSCF_Address),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_ISDN_AddressString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gsmSCF-Address"
		},
	{ ATF_POINTER, 1, offsetof(struct SS_CamelData, extensionContainer),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
};
static const ber_tlv_tag_t asn_DEF_SS_CamelData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SS_CamelData_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* gsmSCF-Address */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* ss-EventList */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 } /* extensionContainer */
};
static asn_SEQUENCE_specifics_t asn_SPC_SS_CamelData_specs_1 = {
	sizeof(struct SS_CamelData),
	offsetof(struct SS_CamelData, _asn_ctx),
	asn_MAP_SS_CamelData_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SS_CamelData = {
	"SS-CamelData",
	"SS-CamelData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SS_CamelData_tags_1,
	sizeof(asn_DEF_SS_CamelData_tags_1)
		/sizeof(asn_DEF_SS_CamelData_tags_1[0]), /* 1 */
	asn_DEF_SS_CamelData_tags_1,	/* Same as above */
	sizeof(asn_DEF_SS_CamelData_tags_1)
		/sizeof(asn_DEF_SS_CamelData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SS_CamelData_1,
	3,	/* Elements count */
	&asn_SPC_SS_CamelData_specs_1	/* Additional specs */
};

