/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-SS-DataTypes"
 * 	found in "MAP-SS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#include "SS-Info.h"

static asn_TYPE_member_t asn_MBR_SS_Info_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SS_Info, choice.forwardingInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ForwardingInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"forwardingInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SS_Info, choice.callBarringInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallBarringInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callBarringInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SS_Info, choice.ss_Data),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SS_Data,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ss-Data"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_SS_Info_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* forwardingInfo */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* callBarringInfo */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 } /* ss-Data */
};
static asn_CHOICE_specifics_t asn_SPC_SS_Info_specs_1 = {
	sizeof(struct SS_Info),
	offsetof(struct SS_Info, _asn_ctx),
	offsetof(struct SS_Info, present),
	sizeof(((struct SS_Info *)0)->present),
	asn_MAP_SS_Info_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SS_Info = {
	"SS-Info",
	"SS-Info",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_SS_Info_1,
	3,	/* Elements count */
	&asn_SPC_SS_Info_specs_1	/* Additional specs */
};

