/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-ER-DataTypes"
 * 	found in "MAP-ER-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#include "SS-IncompatibilityCause.h"

static asn_TYPE_member_t asn_MBR_SS_IncompatibilityCause_1[] = {
	{ ATF_POINTER, 3, offsetof(struct SS_IncompatibilityCause, ss_Code),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SS_Code,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ss-Code"
		},
	{ ATF_POINTER, 2, offsetof(struct SS_IncompatibilityCause, basicService),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_BasicServiceCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"basicService"
		},
	{ ATF_POINTER, 1, offsetof(struct SS_IncompatibilityCause, ss_Status),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SS_Status,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ss-Status"
		},
};
static const ber_tlv_tag_t asn_DEF_SS_IncompatibilityCause_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SS_IncompatibilityCause_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* ss-Code */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* bearerService */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* teleservice */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 2, 0, 0 } /* ss-Status */
};
static asn_SEQUENCE_specifics_t asn_SPC_SS_IncompatibilityCause_specs_1 = {
	sizeof(struct SS_IncompatibilityCause),
	offsetof(struct SS_IncompatibilityCause, _asn_ctx),
	asn_MAP_SS_IncompatibilityCause_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SS_IncompatibilityCause = {
	"SS-IncompatibilityCause",
	"SS-IncompatibilityCause",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SS_IncompatibilityCause_tags_1,
	sizeof(asn_DEF_SS_IncompatibilityCause_tags_1)
		/sizeof(asn_DEF_SS_IncompatibilityCause_tags_1[0]), /* 1 */
	asn_DEF_SS_IncompatibilityCause_tags_1,	/* Same as above */
	sizeof(asn_DEF_SS_IncompatibilityCause_tags_1)
		/sizeof(asn_DEF_SS_IncompatibilityCause_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SS_IncompatibilityCause_1,
	3,	/* Elements count */
	&asn_SPC_SS_IncompatibilityCause_specs_1	/* Additional specs */
};

