/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#include "VlrCamelSubscriptionInfo.h"

static asn_TYPE_member_t asn_MBR_VlrCamelSubscriptionInfo_1[] = {
	{ ATF_POINTER, 12, offsetof(struct VlrCamelSubscriptionInfo, o_CSI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_O_CSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"o-CSI"
		},
	{ ATF_POINTER, 11, offsetof(struct VlrCamelSubscriptionInfo, extensionContainer),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
	{ ATF_POINTER, 10, offsetof(struct VlrCamelSubscriptionInfo, ss_CSI),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SS_CSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ss-CSI"
		},
	{ ATF_POINTER, 9, offsetof(struct VlrCamelSubscriptionInfo, o_BcsmCamelTDP_CriteriaList),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_O_BcsmCamelTDPCriteriaList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"o-BcsmCamelTDP-CriteriaList"
		},
	{ ATF_POINTER, 8, offsetof(struct VlrCamelSubscriptionInfo, tif_CSI),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tif-CSI"
		},
	{ ATF_POINTER, 7, offsetof(struct VlrCamelSubscriptionInfo, m_CSI),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_M_CSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"m-CSI"
		},
	{ ATF_POINTER, 6, offsetof(struct VlrCamelSubscriptionInfo, mo_sms_CSI),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SMS_CSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mo-sms-CSI"
		},
	{ ATF_POINTER, 5, offsetof(struct VlrCamelSubscriptionInfo, vt_CSI),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_T_CSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vt-CSI"
		},
	{ ATF_POINTER, 4, offsetof(struct VlrCamelSubscriptionInfo, t_BCSM_CAMEL_TDP_CriteriaList),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_T_BCSM_CAMEL_TDP_CriteriaList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"t-BCSM-CAMEL-TDP-CriteriaList"
		},
	{ ATF_POINTER, 3, offsetof(struct VlrCamelSubscriptionInfo, d_CSI),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_D_CSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"d-CSI"
		},
	{ ATF_POINTER, 2, offsetof(struct VlrCamelSubscriptionInfo, mt_sms_CSI),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SMS_CSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mt-sms-CSI"
		},
	{ ATF_POINTER, 1, offsetof(struct VlrCamelSubscriptionInfo, mt_smsCAMELTDP_CriteriaList),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MT_smsCAMELTDP_CriteriaList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mt-smsCAMELTDP-CriteriaList"
		},
};
static const ber_tlv_tag_t asn_DEF_VlrCamelSubscriptionInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_VlrCamelSubscriptionInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* o-CSI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* extensionContainer */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ss-CSI */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 4, 0, 0 }, /* tif-CSI */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* o-BcsmCamelTDP-CriteriaList */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* m-CSI */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* mo-sms-CSI */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* vt-CSI */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* t-BCSM-CAMEL-TDP-CriteriaList */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* d-CSI */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* mt-sms-CSI */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 } /* mt-smsCAMELTDP-CriteriaList */
};
static asn_SEQUENCE_specifics_t asn_SPC_VlrCamelSubscriptionInfo_specs_1 = {
	sizeof(struct VlrCamelSubscriptionInfo),
	offsetof(struct VlrCamelSubscriptionInfo, _asn_ctx),
	asn_MAP_VlrCamelSubscriptionInfo_tag2el_1,
	12,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* Start extensions */
	13	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_VlrCamelSubscriptionInfo = {
	"VlrCamelSubscriptionInfo",
	"VlrCamelSubscriptionInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_VlrCamelSubscriptionInfo_tags_1,
	sizeof(asn_DEF_VlrCamelSubscriptionInfo_tags_1)
		/sizeof(asn_DEF_VlrCamelSubscriptionInfo_tags_1[0]), /* 1 */
	asn_DEF_VlrCamelSubscriptionInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_VlrCamelSubscriptionInfo_tags_1)
		/sizeof(asn_DEF_VlrCamelSubscriptionInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_VlrCamelSubscriptionInfo_1,
	12,	/* Elements count */
	&asn_SPC_VlrCamelSubscriptionInfo_specs_1	/* Additional specs */
};

