/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-MS-DataTypes"
 * 	found in "MAP-MS-DataTypes.asn"
 * 	`asn1c -pdu=auto`
 */

#include "VoiceBroadcastData.h"

static asn_TYPE_member_t asn_MBR_VoiceBroadcastData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VoiceBroadcastData, groupid),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_GroupId,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"groupid"
		},
	{ ATF_POINTER, 3, offsetof(struct VoiceBroadcastData, broadcastInitEntitlement),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"broadcastInitEntitlement"
		},
	{ ATF_POINTER, 2, offsetof(struct VoiceBroadcastData, extensionContainer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ExtensionContainer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensionContainer"
		},
	{ ATF_POINTER, 1, offsetof(struct VoiceBroadcastData, longGroupId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Long_GroupId,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"longGroupId"
		},
};
static const ber_tlv_tag_t asn_DEF_VoiceBroadcastData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_VoiceBroadcastData_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* groupid */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 1, 0, 0 }, /* broadcastInitEntitlement */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* extensionContainer */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 3, 0, 0 } /* longGroupId */
};
static asn_SEQUENCE_specifics_t asn_SPC_VoiceBroadcastData_specs_1 = {
	sizeof(struct VoiceBroadcastData),
	offsetof(struct VoiceBroadcastData, _asn_ctx),
	asn_MAP_VoiceBroadcastData_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_VoiceBroadcastData = {
	"VoiceBroadcastData",
	"VoiceBroadcastData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_VoiceBroadcastData_tags_1,
	sizeof(asn_DEF_VoiceBroadcastData_tags_1)
		/sizeof(asn_DEF_VoiceBroadcastData_tags_1[0]), /* 1 */
	asn_DEF_VoiceBroadcastData_tags_1,	/* Same as above */
	sizeof(asn_DEF_VoiceBroadcastData_tags_1)
		/sizeof(asn_DEF_VoiceBroadcastData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_VoiceBroadcastData_1,
	4,	/* Elements count */
	&asn_SPC_VoiceBroadcastData_specs_1	/* Additional specs */
};

