#!/bin/bash
eval writes=$1
eval max=$2
eval sleept=$3 
eval logdate=$4
eval start=$(($(date +%s%N)/1000000))

./writehell log/hei00_$logdate $writes $max $sleept &
./writehell log/hei01_$logdate $writes $max $sleept &
./writehell log/hei02_$logdate $writes $max $sleept &
./writehell log/hei03_$logdate $writes $max $sleept &
./writehell log/hei04_$logdate $writes $max $sleept &
./writehell log/hei05_$logdate $writes $max $sleept &
./writehell log/hei06_$logdate $writes $max $sleept &
./writehell log/hei07_$logdate $writes $max $sleept &
./writehell log/hei08_$logdate $writes $max $sleept &
./writehell log/hei09_$logdate $writes $max $sleept &
./writehell log/hei0a_$logdate $writes $max $sleept &
./writehell log/hei0b_$logdate $writes $max $sleept &
./writehell log/hei0c_$logdate $writes $max $sleept &
./writehell log/hei0d_$logdate $writes $max $sleept &
./writehell log/hei0e_$logdate $writes $max $sleept &
./writehell log/hei0f_$logdate $writes $max $sleept &
./writehell log/hei0g_$logdate $writes $max $sleept &
./writehell log/hei0h_$logdate $writes $max $sleept &
./writehell log/hei0i_$logdate $writes $max $sleept &
./writehell log/hei0j_$logdate $writes $max $sleept &
./writehell log/hei0k_$logdate $writes $max $sleept &
./writehell log/hei0l_$logdate $writes $max $sleept &
./writehell log/hei0m_$logdate $writes $max $sleept &
./writehell log/hei0n_$logdate $writes $max $sleept &
./writehell log/hei0o_$logdate $writes $max $sleept &
./writehell log/hei0p_$logdate $writes $max $sleept &
./writehell log/hei0q_$logdate $writes $max $sleept &
./writehell log/hei0r_$logdate $writes $max $sleept &
./writehell log/hei0s_$logdate $writes $max $sleept &
./writehell log/hei0t_$logdate $writes $max $sleept &
./writehell log/hei0u_$logdate $writes $max $sleept &
./writehell log/hei0v_$logdate $writes $max $sleept &
./writehell log/hei0w_$logdate $writes $max $sleept &
./writehell log/hei0x_$logdate $writes $max $sleept &
./writehell log/hei0y_$logdate $writes $max $sleept &
./writehell log/hei0z_$logdate $writes $max $sleept &
./writehell log/hei0A_$logdate $writes $max $sleept &
./writehell log/hei0B_$logdate $writes $max $sleept &
./writehell log/hei0C_$logdate $writes $max $sleept &
./writehell log/hei0D_$logdate $writes $max $sleept &
./writehell log/hei0E_$logdate $writes $max $sleept &
./writehell log/hei0F_$logdate $writes $max $sleept &
./writehell log/hei0G_$logdate $writes $max $sleept &
./writehell log/hei0H_$logdate $writes $max $sleept &
./writehell log/hei0I_$logdate $writes $max $sleept &
./writehell log/hei0J_$logdate $writes $max $sleept &
./writehell log/hei0K_$logdate $writes $max $sleept &
./writehell log/hei0L_$logdate $writes $max $sleept &
./writehell log/hei0M_$logdate $writes $max $sleept &
./writehell log/hei0N_$logdate $writes $max $sleept &
./writehell log/hei0O_$logdate $writes $max $sleept &
./writehell log/hei0P_$logdate $writes $max $sleept &
./writehell log/hei0Q_$logdate $writes $max $sleept &
./writehell log/hei0R_$logdate $writes $max $sleept &
./writehell log/hei0S_$logdate $writes $max $sleept &
./writehell log/hei0T_$logdate $writes $max $sleept &
./writehell log/hei0U_$logdate $writes $max $sleept &
./writehell log/hei0V_$logdate $writes $max $sleept &
./writehell log/hei0W_$logdate $writes $max $sleept &
./writehell log/hei0X_$logdate $writes $max $sleept &
./writehell log/hei0Y_$logdate $writes $max $sleept &
./writehell log/hei0Z_$logdate $writes $max $sleept &


./writehell log/hei10_$logdate $writes $max $sleept &
./writehell log/hei11_$logdate $writes $max $sleept &
./writehell log/hei12_$logdate $writes $max $sleept &
./writehell log/hei13_$logdate $writes $max $sleept &
./writehell log/hei14_$logdate $writes $max $sleept &
./writehell log/hei15_$logdate $writes $max $sleept &
./writehell log/hei16_$logdate $writes $max $sleept &
./writehell log/hei17_$logdate $writes $max $sleept &
./writehell log/hei18_$logdate $writes $max $sleept &
./writehell log/hei19_$logdate $writes $max $sleept &
./writehell log/hei1a_$logdate $writes $max $sleept &
./writehell log/hei1b_$logdate $writes $max $sleept &
./writehell log/hei1c_$logdate $writes $max $sleept &
./writehell log/hei1d_$logdate $writes $max $sleept &
./writehell log/hei1e_$logdate $writes $max $sleept &
./writehell log/hei1f_$logdate $writes $max $sleept &
./writehell log/hei1g_$logdate $writes $max $sleept &
./writehell log/hei1h_$logdate $writes $max $sleept &
./writehell log/hei1i_$logdate $writes $max $sleept &
./writehell log/hei1j_$logdate $writes $max $sleept &
./writehell log/hei1k_$logdate $writes $max $sleept &
./writehell log/hei1l_$logdate $writes $max $sleept &
./writehell log/hei1m_$logdate $writes $max $sleept &
./writehell log/hei1n_$logdate $writes $max $sleept &
./writehell log/hei1o_$logdate $writes $max $sleept &
./writehell log/hei1p_$logdate $writes $max $sleept &
./writehell log/hei1q_$logdate $writes $max $sleept &
./writehell log/hei1r_$logdate $writes $max $sleept &
./writehell log/hei1s_$logdate $writes $max $sleept &
./writehell log/hei1t_$logdate $writes $max $sleept &
./writehell log/hei1u_$logdate $writes $max $sleept &
./writehell log/hei1v_$logdate $writes $max $sleept &
./writehell log/hei1w_$logdate $writes $max $sleept &
./writehell log/hei1x_$logdate $writes $max $sleept &
./writehell log/hei1y_$logdate $writes $max $sleept &
./writehell log/hei1z_$logdate $writes $max $sleept &
./writehell log/hei1A_$logdate $writes $max $sleept &
./writehell log/hei1B_$logdate $writes $max $sleept &
./writehell log/hei1C_$logdate $writes $max $sleept &
./writehell log/hei1D_$logdate $writes $max $sleept &
./writehell log/hei1E_$logdate $writes $max $sleept &
./writehell log/hei1F_$logdate $writes $max $sleept &
./writehell log/hei1G_$logdate $writes $max $sleept &
./writehell log/hei1H_$logdate $writes $max $sleept &
./writehell log/hei1I_$logdate $writes $max $sleept &
./writehell log/hei1J_$logdate $writes $max $sleept &
./writehell log/hei1K_$logdate $writes $max $sleept &
./writehell log/hei1L_$logdate $writes $max $sleept &
./writehell log/hei1M_$logdate $writes $max $sleept &
./writehell log/hei1N_$logdate $writes $max $sleept &
./writehell log/hei1O_$logdate $writes $max $sleept &
./writehell log/hei1P_$logdate $writes $max $sleept &
./writehell log/hei1Q_$logdate $writes $max $sleept &
./writehell log/hei1R_$logdate $writes $max $sleept &
./writehell log/hei1S_$logdate $writes $max $sleept &
./writehell log/hei1T_$logdate $writes $max $sleept &
./writehell log/hei1U_$logdate $writes $max $sleept &
./writehell log/hei1V_$logdate $writes $max $sleept &
./writehell log/hei1W_$logdate $writes $max $sleept &
./writehell log/hei1X_$logdate $writes $max $sleept &
./writehell log/hei1Y_$logdate $writes $max $sleept &
./writehell log/hei1Z_$logdate $writes $max $sleept &


./writehell log/hei20_$logdate $writes $max $sleept &
./writehell log/hei21_$logdate $writes $max $sleept &
./writehell log/hei22_$logdate $writes $max $sleept &
./writehell log/hei23_$logdate $writes $max $sleept &
./writehell log/hei24_$logdate $writes $max $sleept &
./writehell log/hei25_$logdate $writes $max $sleept &
./writehell log/hei26_$logdate $writes $max $sleept &
./writehell log/hei27_$logdate $writes $max $sleept &
./writehell log/hei28_$logdate $writes $max $sleept &
./writehell log/hei29_$logdate $writes $max $sleept &
./writehell log/hei2a_$logdate $writes $max $sleept &
./writehell log/hei2b_$logdate $writes $max $sleept &
./writehell log/hei2c_$logdate $writes $max $sleept &
./writehell log/hei2d_$logdate $writes $max $sleept &
./writehell log/hei2e_$logdate $writes $max $sleept &
./writehell log/hei2f_$logdate $writes $max $sleept &
./writehell log/hei2g_$logdate $writes $max $sleept &
./writehell log/hei2h_$logdate $writes $max $sleept &
./writehell log/hei2i_$logdate $writes $max $sleept &
./writehell log/hei2j_$logdate $writes $max $sleept &
./writehell log/hei2k_$logdate $writes $max $sleept &
./writehell log/hei2l_$logdate $writes $max $sleept &
./writehell log/hei2m_$logdate $writes $max $sleept &
./writehell log/hei2n_$logdate $writes $max $sleept &
./writehell log/hei2o_$logdate $writes $max $sleept &
./writehell log/hei2p_$logdate $writes $max $sleept &
./writehell log/hei2q_$logdate $writes $max $sleept &
./writehell log/hei2r_$logdate $writes $max $sleept &
./writehell log/hei2s_$logdate $writes $max $sleept &
./writehell log/hei2t_$logdate $writes $max $sleept &
./writehell log/hei2u_$logdate $writes $max $sleept &
./writehell log/hei2v_$logdate $writes $max $sleept &
./writehell log/hei2w_$logdate $writes $max $sleept &
./writehell log/hei2x_$logdate $writes $max $sleept &
./writehell log/hei2y_$logdate $writes $max $sleept &
./writehell log/hei2z_$logdate $writes $max $sleept &
./writehell log/hei2A_$logdate $writes $max $sleept &
./writehell log/hei2B_$logdate $writes $max $sleept &
./writehell log/hei2C_$logdate $writes $max $sleept &
./writehell log/hei2D_$logdate $writes $max $sleept &
./writehell log/hei2E_$logdate $writes $max $sleept &
./writehell log/hei2F_$logdate $writes $max $sleept &
./writehell log/hei2G_$logdate $writes $max $sleept &
./writehell log/hei2H_$logdate $writes $max $sleept &
./writehell log/hei2I_$logdate $writes $max $sleept &
./writehell log/hei2J_$logdate $writes $max $sleept &
./writehell log/hei2K_$logdate $writes $max $sleept &
./writehell log/hei2L_$logdate $writes $max $sleept &
./writehell log/hei2M_$logdate $writes $max $sleept &
./writehell log/hei2N_$logdate $writes $max $sleept &
./writehell log/hei2O_$logdate $writes $max $sleept &
./writehell log/hei2P_$logdate $writes $max $sleept &
./writehell log/hei2Q_$logdate $writes $max $sleept &
./writehell log/hei2R_$logdate $writes $max $sleept &
./writehell log/hei2S_$logdate $writes $max $sleept &
./writehell log/hei2T_$logdate $writes $max $sleept &
./writehell log/hei2U_$logdate $writes $max $sleept &
./writehell log/hei2V_$logdate $writes $max $sleept &
./writehell log/hei2W_$logdate $writes $max $sleept &
./writehell log/hei2X_$logdate $writes $max $sleept &
./writehell log/hei2Y_$logdate $writes $max $sleept &
./writehell log/hei2Z_$logdate $writes $max $sleept &

wait 
eval end=$(($(date +%s%N)/1000000))
let delta=$end-$start
echo $delta milliseconds

