#!/bin/bash
eval max=$1
eval start=$(($(date +%s%N)/1000000))

./writehell log2/hei00.log $max &
./writehell log2/hei01.log $max &
./writehell log2/hei02.log $max &
./writehell log2/hei03.log $max &
./writehell log2/hei04.log $max &
./writehell log2/hei05.log $max &
./writehell log2/hei06.log $max &
./writehell log2/hei07.log $max &
./writehell log2/hei08.log $max &
./writehell log2/hei09.log $max &
./writehell log2/hei0a.log $max &
./writehell log2/hei0b.log $max &
./writehell log2/hei0c.log $max &
./writehell log2/hei0d.log $max &
./writehell log2/hei0e.log $max &
./writehell log2/hei0f.log $max &
./writehell log2/hei0g.log $max &
./writehell log2/hei0h.log $max &
./writehell log2/hei0i.log $max &
./writehell log2/hei0j.log $max &
./writehell log2/hei0k.log $max &
./writehell log2/hei0l.log $max &
./writehell log2/hei0m.log $max &
./writehell log2/hei0n.log $max &
./writehell log2/hei0o.log $max &
./writehell log2/hei0p.log $max &
./writehell log2/hei0q.log $max &
./writehell log2/hei0r.log $max &
./writehell log2/hei0s.log $max &
./writehell log2/hei0t.log $max &
./writehell log2/hei0u.log $max &
./writehell log2/hei0v.log $max &
./writehell log2/hei0w.log $max &
./writehell log2/hei0x.log $max &
./writehell log2/hei0y.log $max &
./writehell log2/hei0z.log $max &
./writehell log2/hei0A.log $max &
./writehell log2/hei0B.log $max &
./writehell log2/hei0C.log $max &
./writehell log2/hei0D.log $max &
./writehell log2/hei0E.log $max &
./writehell log2/hei0F.log $max &
./writehell log2/hei0G.log $max &
./writehell log2/hei0H.log $max &
./writehell log2/hei0I.log $max &
./writehell log2/hei0J.log $max &
./writehell log2/hei0K.log $max &
./writehell log2/hei0L.log $max &
./writehell log2/hei0M.log $max &
./writehell log2/hei0N.log $max &
./writehell log2/hei0O.log $max &
./writehell log2/hei0P.log $max &
./writehell log2/hei0Q.log $max &
./writehell log2/hei0R.log $max &
./writehell log2/hei0S.log $max &
./writehell log2/hei0T.log $max &
./writehell log2/hei0U.log $max &
./writehell log2/hei0V.log $max &
./writehell log2/hei0W.log $max &
./writehell log2/hei0X.log $max &
./writehell log2/hei0Y.log $max &
./writehell log2/hei0Z.log $max &


./writehell log2/hei10.log $max &
./writehell log2/hei11.log $max &
./writehell log2/hei12.log $max &
./writehell log2/hei13.log $max &
./writehell log2/hei14.log $max &
./writehell log2/hei15.log $max &
./writehell log2/hei16.log $max &
./writehell log2/hei17.log $max &
./writehell log2/hei18.log $max &
./writehell log2/hei19.log $max &
./writehell log2/hei1a.log $max &
./writehell log2/hei1b.log $max &
./writehell log2/hei1c.log $max &
./writehell log2/hei1d.log $max &
./writehell log2/hei1e.log $max &
./writehell log2/hei1f.log $max &
./writehell log2/hei1g.log $max &
./writehell log2/hei1h.log $max &
./writehell log2/hei1i.log $max &
./writehell log2/hei1j.log $max &
./writehell log2/hei1k.log $max &
./writehell log2/hei1l.log $max &
./writehell log2/hei1m.log $max &
./writehell log2/hei1n.log $max &
./writehell log2/hei1o.log $max &
./writehell log2/hei1p.log $max &
./writehell log2/hei1q.log $max &
./writehell log2/hei1r.log $max &
./writehell log2/hei1s.log $max &
./writehell log2/hei1t.log $max &
./writehell log2/hei1u.log $max &
./writehell log2/hei1v.log $max &
./writehell log2/hei1w.log $max &
./writehell log2/hei1x.log $max &
./writehell log2/hei1y.log $max &
./writehell log2/hei1z.log $max &
./writehell log2/hei1A.log $max &
./writehell log2/hei1B.log $max &
./writehell log2/hei1C.log $max &
./writehell log2/hei1D.log $max &
./writehell log2/hei1E.log $max &
./writehell log2/hei1F.log $max &
./writehell log2/hei1G.log $max &
./writehell log2/hei1H.log $max &
./writehell log2/hei1I.log $max &
./writehell log2/hei1J.log $max &
./writehell log2/hei1K.log $max &
./writehell log2/hei1L.log $max &
./writehell log2/hei1M.log $max &
./writehell log2/hei1N.log $max &
./writehell log2/hei1O.log $max &
./writehell log2/hei1P.log $max &
./writehell log2/hei1Q.log $max &
./writehell log2/hei1R.log $max &
./writehell log2/hei1S.log $max &
./writehell log2/hei1T.log $max &
./writehell log2/hei1U.log $max &
./writehell log2/hei1V.log $max &
./writehell log2/hei1W.log $max &
./writehell log2/hei1X.log $max &
./writehell log2/hei1Y.log $max &
./writehell log2/hei1Z.log $max &


./writehell log2/hei20.log $max &
./writehell log2/hei21.log $max &
./writehell log2/hei22.log $max &
./writehell log2/hei23.log $max &
./writehell log2/hei24.log $max &
./writehell log2/hei25.log $max &
./writehell log2/hei26.log $max &
./writehell log2/hei27.log $max &
./writehell log2/hei28.log $max &
./writehell log2/hei29.log $max &
./writehell log2/hei2a.log $max &
./writehell log2/hei2b.log $max &
./writehell log2/hei2c.log $max &
./writehell log2/hei2d.log $max &
./writehell log2/hei2e.log $max &
./writehell log2/hei2f.log $max &
./writehell log2/hei2g.log $max &
./writehell log2/hei2h.log $max &
./writehell log2/hei2i.log $max &
./writehell log2/hei2j.log $max &
./writehell log2/hei2k.log $max &
./writehell log2/hei2l.log $max &
./writehell log2/hei2m.log $max &
./writehell log2/hei2n.log $max &
./writehell log2/hei2o.log $max &
./writehell log2/hei2p.log $max &
./writehell log2/hei2q.log $max &
./writehell log2/hei2r.log $max &
./writehell log2/hei2s.log $max &
./writehell log2/hei2t.log $max &
./writehell log2/hei2u.log $max &
./writehell log2/hei2v.log $max &
./writehell log2/hei2w.log $max &
./writehell log2/hei2x.log $max &
./writehell log2/hei2y.log $max &
./writehell log2/hei2z.log $max &
./writehell log2/hei2A.log $max &
./writehell log2/hei2B.log $max &
./writehell log2/hei2C.log $max &
./writehell log2/hei2D.log $max &
./writehell log2/hei2E.log $max &
./writehell log2/hei2F.log $max &
./writehell log2/hei2G.log $max &
./writehell log2/hei2H.log $max &
./writehell log2/hei2I.log $max &
./writehell log2/hei2J.log $max &
./writehell log2/hei2K.log $max &
./writehell log2/hei2L.log $max &
./writehell log2/hei2M.log $max &
./writehell log2/hei2N.log $max &
./writehell log2/hei2O.log $max &
./writehell log2/hei2P.log $max &
./writehell log2/hei2Q.log $max &
./writehell log2/hei2R.log $max &
./writehell log2/hei2S.log $max &
./writehell log2/hei2T.log $max &
./writehell log2/hei2U.log $max &
./writehell log2/hei2V.log $max &
./writehell log2/hei2W.log $max &
./writehell log2/hei2X.log $max &
./writehell log2/hei2Y.log $max &
./writehell log2/hei2Z.log $max &

wait 
eval end=$(($(date +%s%N)/1000000))
let delta=$end-$start
echo $delta milliseconds

