#!/bin/bash
eval max=$1
eval start=$(($(date +%s%N)/1000000))

./writehell locallog/hei00.log $max &
./writehell locallog/hei01.log $max &
./writehell locallog/hei02.log $max &
./writehell locallog/hei03.log $max &
./writehell locallog/hei04.log $max &
./writehell locallog/hei05.log $max &
./writehell locallog/hei06.log $max &
./writehell locallog/hei07.log $max &
./writehell locallog/hei08.log $max &
./writehell locallog/hei09.log $max &
./writehell locallog/hei0a.log $max &
./writehell locallog/hei0b.log $max &
./writehell locallog/hei0c.log $max &
./writehell locallog/hei0d.log $max &
./writehell locallog/hei0e.log $max &
./writehell locallog/hei0f.log $max &
./writehell locallog/hei0g.log $max &
./writehell locallog/hei0h.log $max &
./writehell locallog/hei0i.log $max &
./writehell locallog/hei0j.log $max &
./writehell locallog/hei0k.log $max &
./writehell locallog/hei0l.log $max &
./writehell locallog/hei0m.log $max &
./writehell locallog/hei0n.log $max &
./writehell locallog/hei0o.log $max &
./writehell locallog/hei0p.log $max &
./writehell locallog/hei0q.log $max &
./writehell locallog/hei0r.log $max &
./writehell locallog/hei0s.log $max &
./writehell locallog/hei0t.log $max &
./writehell locallog/hei0u.log $max &
./writehell locallog/hei0v.log $max &
./writehell locallog/hei0w.log $max &
./writehell locallog/hei0x.log $max &
./writehell locallog/hei0y.log $max &
./writehell locallog/hei0z.log $max &
./writehell locallog/hei0A.log $max &
./writehell locallog/hei0B.log $max &
./writehell locallog/hei0C.log $max &
./writehell locallog/hei0D.log $max &
./writehell locallog/hei0E.log $max &
./writehell locallog/hei0F.log $max &
./writehell locallog/hei0G.log $max &
./writehell locallog/hei0H.log $max &
./writehell locallog/hei0I.log $max &
./writehell locallog/hei0J.log $max &
./writehell locallog/hei0K.log $max &
./writehell locallog/hei0L.log $max &
./writehell locallog/hei0M.log $max &
./writehell locallog/hei0N.log $max &
./writehell locallog/hei0O.log $max &
./writehell locallog/hei0P.log $max &
./writehell locallog/hei0Q.log $max &
./writehell locallog/hei0R.log $max &
./writehell locallog/hei0S.log $max &
./writehell locallog/hei0T.log $max &
./writehell locallog/hei0U.log $max &
./writehell locallog/hei0V.log $max &
./writehell locallog/hei0W.log $max &
./writehell locallog/hei0X.log $max &
./writehell locallog/hei0Y.log $max &
./writehell locallog/hei0Z.log $max &


./writehell locallog/hei10.log $max &
./writehell locallog/hei11.log $max &
./writehell locallog/hei12.log $max &
./writehell locallog/hei13.log $max &
./writehell locallog/hei14.log $max &
./writehell locallog/hei15.log $max &
./writehell locallog/hei16.log $max &
./writehell locallog/hei17.log $max &
./writehell locallog/hei18.log $max &
./writehell locallog/hei19.log $max &
./writehell locallog/hei1a.log $max &
./writehell locallog/hei1b.log $max &
./writehell locallog/hei1c.log $max &
./writehell locallog/hei1d.log $max &
./writehell locallog/hei1e.log $max &
./writehell locallog/hei1f.log $max &
./writehell locallog/hei1g.log $max &
./writehell locallog/hei1h.log $max &
./writehell locallog/hei1i.log $max &
./writehell locallog/hei1j.log $max &
./writehell locallog/hei1k.log $max &
./writehell locallog/hei1l.log $max &
./writehell locallog/hei1m.log $max &
./writehell locallog/hei1n.log $max &
./writehell locallog/hei1o.log $max &
./writehell locallog/hei1p.log $max &
./writehell locallog/hei1q.log $max &
./writehell locallog/hei1r.log $max &
./writehell locallog/hei1s.log $max &
./writehell locallog/hei1t.log $max &
./writehell locallog/hei1u.log $max &
./writehell locallog/hei1v.log $max &
./writehell locallog/hei1w.log $max &
./writehell locallog/hei1x.log $max &
./writehell locallog/hei1y.log $max &
./writehell locallog/hei1z.log $max &
./writehell locallog/hei1A.log $max &
./writehell locallog/hei1B.log $max &
./writehell locallog/hei1C.log $max &
./writehell locallog/hei1D.log $max &
./writehell locallog/hei1E.log $max &
./writehell locallog/hei1F.log $max &
./writehell locallog/hei1G.log $max &
./writehell locallog/hei1H.log $max &
./writehell locallog/hei1I.log $max &
./writehell locallog/hei1J.log $max &
./writehell locallog/hei1K.log $max &
./writehell locallog/hei1L.log $max &
./writehell locallog/hei1M.log $max &
./writehell locallog/hei1N.log $max &
./writehell locallog/hei1O.log $max &
./writehell locallog/hei1P.log $max &
./writehell locallog/hei1Q.log $max &
./writehell locallog/hei1R.log $max &
./writehell locallog/hei1S.log $max &
./writehell locallog/hei1T.log $max &
./writehell locallog/hei1U.log $max &
./writehell locallog/hei1V.log $max &
./writehell locallog/hei1W.log $max &
./writehell locallog/hei1X.log $max &
./writehell locallog/hei1Y.log $max &
./writehell locallog/hei1Z.log $max &


./writehell locallog/hei20.log $max &
./writehell locallog/hei21.log $max &
./writehell locallog/hei22.log $max &
./writehell locallog/hei23.log $max &
./writehell locallog/hei24.log $max &
./writehell locallog/hei25.log $max &
./writehell locallog/hei26.log $max &
./writehell locallog/hei27.log $max &
./writehell locallog/hei28.log $max &
./writehell locallog/hei29.log $max &
./writehell locallog/hei2a.log $max &
./writehell locallog/hei2b.log $max &
./writehell locallog/hei2c.log $max &
./writehell locallog/hei2d.log $max &
./writehell locallog/hei2e.log $max &
./writehell locallog/hei2f.log $max &
./writehell locallog/hei2g.log $max &
./writehell locallog/hei2h.log $max &
./writehell locallog/hei2i.log $max &
./writehell locallog/hei2j.log $max &
./writehell locallog/hei2k.log $max &
./writehell locallog/hei2l.log $max &
./writehell locallog/hei2m.log $max &
./writehell locallog/hei2n.log $max &
./writehell locallog/hei2o.log $max &
./writehell locallog/hei2p.log $max &
./writehell locallog/hei2q.log $max &
./writehell locallog/hei2r.log $max &
./writehell locallog/hei2s.log $max &
./writehell locallog/hei2t.log $max &
./writehell locallog/hei2u.log $max &
./writehell locallog/hei2v.log $max &
./writehell locallog/hei2w.log $max &
./writehell locallog/hei2x.log $max &
./writehell locallog/hei2y.log $max &
./writehell locallog/hei2z.log $max &
./writehell locallog/hei2A.log $max &
./writehell locallog/hei2B.log $max &
./writehell locallog/hei2C.log $max &
./writehell locallog/hei2D.log $max &
./writehell locallog/hei2E.log $max &
./writehell locallog/hei2F.log $max &
./writehell locallog/hei2G.log $max &
./writehell locallog/hei2H.log $max &
./writehell locallog/hei2I.log $max &
./writehell locallog/hei2J.log $max &
./writehell locallog/hei2K.log $max &
./writehell locallog/hei2L.log $max &
./writehell locallog/hei2M.log $max &
./writehell locallog/hei2N.log $max &
./writehell locallog/hei2O.log $max &
./writehell locallog/hei2P.log $max &
./writehell locallog/hei2Q.log $max &
./writehell locallog/hei2R.log $max &
./writehell locallog/hei2S.log $max &
./writehell locallog/hei2T.log $max &
./writehell locallog/hei2U.log $max &
./writehell locallog/hei2V.log $max &
./writehell locallog/hei2W.log $max &
./writehell locallog/hei2X.log $max &
./writehell locallog/hei2Y.log $max &
./writehell locallog/hei2Z.log $max &

wait 
eval end=$(($(date +%s%N)/1000000))
let delta=$end-$start
echo $delta milliseconds

