all: septet_to_octet.c pdu_ascii.c  test_shift.c gsm_pdu.c gsm_pdux.c
	gcc -Wall -ggdb3 septet_to_octet.c -o septet_to_octet
	gcc -Wall -ggdb3 pdu_ascii.c -o pdu_ascii
	gcc -Wall -ggdb3 gsm_pdu.c -o gsm_pdu
	gcc -Wall -ggdb3 gsm_pdux.c -o gsm_pdux
#	gcc -Wall -ggdb3 test_shift.c -o test_shift
